// The roster. Stats are multipliers around 1 (hp is absolute).
// Specials come in four flavors, handled in engine.js:
//   projectile — throws something across the screen
//   dash       — charges forward, hitting whatever is in the way
//   uppercut   — rising attack that launches the foe
//   slam       — hop up and crash down, shockwave hits grounded foes nearby
// `gimmick` tweaks how an animal fights (all optional):
//   lightMult/heavyMult — damage of light/heavy attacks, attackSpeed — how fast attacks come out,
//   reach — attack range, airMult — damage while in the air, shell — blocks from both sides,
//   chip — how much damage still gets through a block.
// `say` is how the talking voice should pronounce the name; `voice` is its pitch and speed.
// `unlock` (optional): 'wins:N' after N wins, 'secret' for a hidden code, 'boss' for beating Arcade.
// The first quote is the classic; the winner says a random one.
export const FIGHTERS = [
  {
    key: 'hitopotamus', name: 'Hit-opotamus', emoji: '🦛', pun: 'hippo + hit', say: 'Hit oh pot a mus',
    voice: { pitch: 0.3, rate: 0.8 }, color: '#8d7aa8',
    hp: 118, speed: 0.72, power: 1.1, jump: 0.85,
    gimmick: { lightMult: 1.45, heavyMult: 1.35, attackSpeed: 0.85, text: 'HUGE punches, slow feet' },
    special: { type: 'slam', name: 'Belly Flop', dmg: 18, radius: 190 },
    superName: 'Hippo-calypse',
    quotes: ['HIPPO-CALYPSE NOW.', "I'm not fat. I'm fight-sized.", 'Hungry, hungry for VICTORY!'],
  },
  {
    key: 'geckow', name: 'Geck-OW', emoji: '🦎', pun: 'gecko + OW!', say: 'Gecko ow',
    voice: { pitch: 1.9, rate: 1.3 }, color: '#5cc24a',
    hp: 106, speed: 1.3, power: 1.04, jump: 1.2,
    gimmick: { text: 'Quick and slippery' },
    special: { type: 'uppercut', name: 'Tail Flip', dmg: 14 },
    superName: 'Geck-OW-zilla',
    quotes: ["Ow! That's gotta hurt!", "I'd stick around, but I already won.", 'I saved fifteen percent on beating you.'],
  },
  {
    key: 'pandamonium', name: 'Panda-monium', emoji: '🐼', pun: 'panda + pandemonium', say: 'Panda monium',
    voice: { pitch: 1.1, rate: 1.0 }, color: '#e8e8e8',
    hp: 110, speed: 0.95, power: 1.02, jump: 0.95,
    gimmick: { text: 'Rolls right over you' },
    special: { type: 'dash', name: 'Bamboo Roll', dmg: 14, speed: 720 },
    superName: 'Panda-monium Frenzy',
    quotes: ['Total panda-monium!', 'Black, white, and victorious all over.', "I'm bam-BOO-zled you even tried."],
  },
  {
    key: 'crocadial', name: 'Croc-a-dial', emoji: '🐊', pun: 'croc + dial', say: 'Croc a dial',
    voice: { pitch: 0.5, rate: 0.85 }, color: '#3f8a4a',
    hp: 106, speed: 0.9, power: 1.05, jump: 0.85,
    gimmick: { text: 'Tough scales, big bite' },
    special: { type: 'dash', name: 'Death Roll', dmg: 17, speed: 620 },
    superName: 'Tick-Tock Croc Shock',
    quotes: ['Better dial a doctor!', 'See you later... or not!', "In a while, crocodile? I'm here to stay."],
  },
  {
    key: 'lionheart', name: 'Lion-Heart', emoji: '🦁', pun: 'lion + lionhearted', say: 'Lion heart',
    voice: { pitch: 0.7, rate: 0.95 }, color: '#e0a23a',
    hp: 108, speed: 1.0, power: 1.05, jump: 1,
    gimmick: { text: 'All-rounder with a roar' },
    special: { type: 'projectile', name: 'Roar Blast', dmg: 15, speed: 520, emoji: '🔥', size: 44 },
    superName: 'Pride of the Jungle',
    quotes: ['Brave to the very end!', 'Hear me ROAR... and weep.', 'The mane event is OVER.'],
  },
  {
    key: 'bearknuckle', name: 'Bear-knuckle', emoji: '🐻', pun: 'bear + bare-knuckle', say: 'Bear knuckle',
    voice: { pitch: 0.4, rate: 0.85 }, color: '#8a5a32',
    hp: 108, speed: 0.92, power: 1.05, jump: 0.9,
    gimmick: { heavyMult: 1.05, text: 'Heavy paws, heavy hits' },
    special: { type: 'dash', name: 'Knuckle Rush', dmg: 16, speed: 680 },
    superName: 'Un-BEAR-able Barrage',
    quotes: ['Bear with me. You lost!', 'That was un-BEAR-able for you.', 'Back to hibernating. Wake me for a real challenge.'],
  },
  {
    key: 'beestmode', name: 'Bee-st Mode', emoji: '🐝', pun: 'bee + beast mode', say: 'Beast mode',
    voice: { pitch: 2.0, rate: 1.4 }, color: '#f2c40c',
    hp: 100, speed: 1.3, power: 1.1, jump: 1.25,
    gimmick: { text: 'Hovers and stings' },
    special: { type: 'projectile', name: 'Stinger Shot', dmg: 12, speed: 780, emoji: '⚡', size: 32 },
    superName: 'Buzz Saw',
    quotes: ['Bee-st mode, activated!', 'Buzz off!', 'You just got STUNG by greatness.'],
  },
  {
    key: 'kickahorse', name: 'Kick-a-horse', emoji: '🐴', pun: 'kick + horse', say: 'Kick a horse',
    voice: { pitch: 1.2, rate: 1.15 }, color: '#a86a3d',
    hp: 104, speed: 1.15, power: 1.02, jump: 1.1,
    gimmick: { heavyMult: 1.2, reach: 1.1, text: 'Kicks like a... well, horse' },
    special: { type: 'dash', name: 'Gallop Kick', dmg: 15, speed: 820 },
    superName: 'Hold Your Horses',
    quotes: ['Neigh-body beats me!', 'Hay, better luck next time.', 'Stop horsing around and admit I am the best.'],
  },
  {
    key: 'sharkitecture', name: 'Shark-itecture', emoji: '🦈', pun: 'shark + architecture', say: 'Sharkitecture',
    voice: { pitch: 0.8, rate: 1.0 }, color: '#5a8ab8',
    hp: 108, speed: 1.0, power: 1.05, jump: 0.95,
    gimmick: { text: 'Builds a wall of water' },
    special: { type: 'projectile', name: 'Tidal Wave', dmg: 16, speed: 380, emoji: '🌊', size: 58 },
    superName: 'Jaws of Destruction',
    quotes: ['I built this victory!', 'That fight was a real FIN-ale.', 'The blueprints said you would lose.'],
  },
  {
    key: 'duckandcover', name: 'Duck and Cover', emoji: '🦆', pun: 'duck + fighting phrase', say: 'Duck and cover',
    voice: { pitch: 1.7, rate: 1.25 }, color: '#6b8f3a',
    hp: 104, speed: 1.15, power: 1.02, jump: 1.15,
    gimmick: { text: 'Lobs eggs from cover' },
    special: { type: 'projectile', name: 'Egg Grenade', dmg: 15, speed: 560, emoji: '🥚', size: 36 },
    superName: 'Duck Duck GOOSE',
    quotes: ['You should have ducked!', 'Quack attack complete.', 'Get the flock out of my arena!'],
  },
  {
    key: 'hissterical', name: 'Hiss-terical', emoji: '🐍', pun: 'hiss + hysterical', say: 'Hiss terical',
    voice: { pitch: 1.4, rate: 0.9 }, color: '#4aa84a',
    hp: 102, speed: 1.2, power: 1.03, jump: 0.95,
    gimmick: { reach: 1.1, text: 'Long, sneaky strikes' },
    special: { type: 'projectile', name: 'Venom Spit', dmg: 13, speed: 700, emoji: '🟢', size: 26 },
    superName: 'Hiss-tory Lesson',
    quotes: ['Hisss-terical!', 'Sssso long, sucker!', 'That was sssuper easy.'],
  },
  {
    key: 'crabbat', name: 'Crab-bat', emoji: '🦀', pun: 'crab + combat', say: 'Crab bat',
    voice: { pitch: 1.5, rate: 1.2 }, color: '#e0503a',
    hp: 112, speed: 1.3, power: 1.05, jump: 0.9,
    gimmick: { reach: 1.25, text: 'Scuttles sideways, long claws' },
    special: { type: 'uppercut', name: 'Claw Snap', dmg: 13 },
    superName: 'Claw-some Crush',
    quotes: ['You got CRUSHED sideways.', "Don't be so crabby!", "I'm feeling pretty shellfish about this win."],
  },
  {
    key: 'octopunch', name: 'Octo-Punch', emoji: '🐙', pun: 'octopus + punch', say: 'Octo punch',
    voice: { pitch: 1.3, rate: 1.1 }, color: '#d0508a',
    hp: 106, speed: 1.0, power: 1.05, jump: 1,
    gimmick: { attackSpeed: 1.03, text: 'So many arms, so many punches' },
    special: { type: 'projectile', name: 'Ink Blast', dmg: 15, speed: 560, emoji: '⚫', size: 36 },
    superName: 'Eight-Fold Fury',
    quotes: ['Eight arms. Zero mercy!', "I've got my hands full... of VICTORY.", 'Ink-credible, right?'],
  },
  {
    key: 'gorillawarfare', name: 'Gorilla Warfare', emoji: '🦍', pun: 'gorilla + guerrilla warfare', say: 'Gorilla warfare',
    voice: { pitch: 0.3, rate: 0.8 }, color: '#4a4a55',
    hp: 124, speed: 0.95, power: 1.1, jump: 0.95,
    gimmick: { reach: 1.1, text: 'Long arms, ground pounds' },
    special: { type: 'slam', name: 'Ground Pound', dmg: 19, radius: 210 },
    superName: 'Go Bananas',
    quotes: ['Ape-solutely crushed!', 'Going BANANAS!', 'Talk to the hand. All four of them.'],
  },
  {
    key: 'goatnglory', name: 'Goat-n Glory', emoji: '🐐', pun: 'goat + glory', say: 'Goat and glory',
    voice: { pitch: 1.0, rate: 1.05 }, color: '#cfc4a8',
    hp: 110, speed: 1.05, power: 1.06, jump: 1.2,
    gimmick: { text: 'Headbutts to glory' },
    special: { type: 'uppercut', name: 'Horn Launcher', dmg: 13 },
    superName: 'G.O.A.T. Rush',
    quotes: ['Greatest of all time!', 'You just got BUTTED out.', 'Baaaaa-d luck, buddy.'],
  },
  {
    key: 'wolfpack', name: 'Wolf Pack', emoji: '🐺', pun: 'wolf + pack', say: 'Wolf pack',
    voice: { pitch: 0.6, rate: 0.95 }, color: '#7a8494',
    hp: 106, speed: 1.15, power: 1.05, jump: 1.05,
    gimmick: { text: 'Never fights alone' },
    special: { type: 'projectile', name: 'Call the Pack', dmg: 17, speed: 600, emoji: '🐺', size: 48 },
    superName: 'Howl-elujah',
    quotes: ['Awoooooo!', "Who's afraid of the big bad wolf? You. Now.", 'The pack says hi.'],
  },
  {
    key: 'rhinomite', name: 'Rhino-Mite', emoji: '🦏', pun: 'rhino + dynamite', say: 'Rhino mite',
    voice: { pitch: 0.35, rate: 0.9 }, color: '#8f8f9c',
    hp: 112, speed: 0.85, power: 1.05, jump: 0.8,
    gimmick: { text: 'Charges across the whole arena' },
    special: { type: 'dash', name: 'Dynamite Charge', dmg: 15, speed: 900, dur: 0.95 },
    superName: 'Rhino-Mite KABOOM',
    quotes: ['Kaboom! Rhino-mite!', 'I charge by the hit. That will be a LOT.', 'Horns up, you are down.'],
  },
  {
    key: 'frogment', name: 'Frog-ment', emoji: '🐸', pun: 'frog + fragment', say: 'Frog ment',
    voice: { pitch: 1.6, rate: 1.2 }, color: '#6cc24a',
    hp: 106, speed: 1.1, power: 1.04, jump: 1.55,
    gimmick: { text: 'SUPER jump' },
    special: { type: 'uppercut', name: 'Leap Frog', dmg: 14 },
    superName: 'Hop To It',
    quotes: ['That was a LEAP above the competition.', 'Toad-ally smashed!', "Ribbit ribbit. That means 'you lose'."],
  },
  {
    key: 'chimpchamp', name: 'Chimp Champ', emoji: '🐒', pun: 'chimp + champ', say: 'Chimp champ',
    voice: { pitch: 1.5, rate: 1.35 }, color: '#8a5a3a',
    hp: 98, speed: 1.25, power: 1.0, jump: 1.15,
    gimmick: { attackSpeed: 1.4, lightMult: 0.95, text: 'Lightning-fast combos' },
    special: { type: 'projectile', name: 'Banana Toss', dmg: 13, speed: 620, emoji: '🍌', size: 36 },
    superName: 'Monkey Business',
    quotes: ['Monkey see, monkey WIN!', 'That was BANANAS!', 'Oo oo AH AH! Champion!'],
  },
  {
    key: 'kangaroo', name: 'Kanga-Roo', emoji: '🦘', pun: 'kangaroo + boxing roo', say: 'Kanga roo',
    voice: { pitch: 1.1, rate: 1.1 }, color: '#c08a52',
    hp: 116, speed: 1.05, power: 1.1, jump: 1.45,
    gimmick: { airMult: 1.5, text: 'Giant jumping attacks' },
    special: { type: 'slam', name: 'Boing Bounce', dmg: 17, radius: 200 },
    superName: 'Outback Outburst',
    unlock: 'wins:3',
    quotes: ['Hop, hop, HOORAY!', "I've got a pouch full of wins.", "G'day! And good-BYE!"],
  },
  {
    key: 'shellshock', name: 'Shell-Shock', emoji: '🐢', pun: 'shell + shell-shock', say: 'Shell shock',
    voice: { pitch: 0.6, rate: 0.75 }, color: '#4a9a5a',
    hp: 112, speed: 0.8, power: 1.02, jump: 0.8,
    gimmick: { shell: true, chip: 0, text: 'Hides in its shell: blocks EVERYTHING' },
    special: { type: 'dash', name: 'Shell Spin', dmg: 15, speed: 700 },
    superName: 'Shell Shocker',
    unlock: 'wins:6',
    quotes: ['Slow and steady wins the brawl.', 'Shell yeah!', 'You came out of your shell. Mistake.'],
  },
  {
    key: 'slothmo', name: 'Sloth-Mo', emoji: '🦥', pun: 'sloth + slow-mo', say: 'Sloth moe',
    voice: { pitch: 0.5, rate: 0.55 }, color: '#9a8468',
    hp: 125, speed: 0.6, power: 1.25, jump: 0.8,
    gimmick: { attackSpeed: 0.75, text: 'SO slow. SO strong.' },
    special: { type: 'slam', name: 'Nap Attack', dmg: 20, radius: 200 },
    superName: 'Slow-Motion Smackdown',
    unlock: 'secret',
    quotes: ['Zzzz... oh... I won?', 'Worth... the... wait.', 'Fastest... win... EVER.'],
  },
  {
    key: 'moosclebeast', name: 'Moo-scle Beast', emoji: '🐄', pun: 'moo + muscle', say: 'Moo-scle beast',
    voice: { pitch: 0.2, rate: 0.75 }, color: '#f0f0f0',
    hp: 112, speed: 0.95, power: 1.04, jump: 0.9,
    gimmick: { heavyMult: 1.0, text: 'THE BOSS. Udderly unstoppable.' },
    special: { type: 'dash', name: 'Stampede', dmg: 15, speed: 850, dur: 0.8 },
    superName: 'Udder Destruction',
    unlock: 'boss',
    boss: true,
    quotes: ['Udder-ly defeated!', 'MOO-ve aside. Champ coming through.', "That's no bull. I'm the BOSS."],
  },
]

export const BOSS = FIGHTERS.find((f) => f.boss)
export const byKey = (key) => FIGHTERS.find((f) => f.key === key)

// The arcade-mode boss is extra tough.
export function bossVersion(def) {
  return { ...def, hp: 260, power: 1.3 }
}
