// The roster. Stats are multipliers around 1 (hp is absolute).
// Specials come in four flavors, handled in engine.js:
//   projectile — throws something across the screen
//   dash       — charges forward, hitting whatever is in the way
//   uppercut   — rising attack that launches the foe
//   slam       — hop up and crash down, shockwave hits grounded foes nearby
// `say` is how the talking voice should pronounce the name; `voice` is its pitch and speed.
export const FIGHTERS = [
  {
    key: 'hitopotamus',
    name: 'Hit-opotamus',
    emoji: '🦛',
    pun: 'hippo + hit',
    say: 'Hit oh pot a mus',
    voice: { pitch: 0.3, rate: 0.8 },
    win: 'That was hippo-tastic!',
    color: '#8d7aa8',
    hp: 122,
    speed: 0.8,
    power: 1.1,
    jump: 0.85,
    special: { type: 'slam', name: 'Belly Flop', dmg: 18, radius: 190 },
  },
  {
    key: 'geckow',
    name: 'Geck-OW',
    emoji: '🦎',
    pun: 'gecko + OW!',
    say: 'Gecko ow',
    voice: { pitch: 1.9, rate: 1.3 },
    win: "Ow! That's gotta hurt!",
    color: '#5cc24a',
    hp: 100,
    speed: 1.3,
    power: 1.0,
    jump: 1.2,
    special: { type: 'uppercut', name: 'Tail Flip', dmg: 14 },
  },
  {
    key: 'pandamonium',
    name: 'Panda-monium',
    emoji: '🐼',
    pun: 'panda + pandemonium',
    say: 'Panda monium',
    voice: { pitch: 1.1, rate: 1.0 },
    win: 'Total panda-monium!',
    color: '#e8e8e8',
    hp: 110,
    speed: 0.95,
    power: 1.02,
    jump: 0.95,
    special: { type: 'dash', name: 'Bamboo Roll', dmg: 14, speed: 720 },
  },
  {
    key: 'crocadial',
    name: 'Croc-a-dial',
    emoji: '🐊',
    pun: 'croc + dial',
    say: 'Croc a dial',
    voice: { pitch: 0.5, rate: 0.85 },
    win: 'Better dial a doctor!',
    color: '#3f8a4a',
    hp: 110,
    speed: 0.9,
    power: 1.05,
    jump: 0.85,
    special: { type: 'dash', name: 'Death Roll', dmg: 17, speed: 620 },
  },
  {
    key: 'lionheart',
    name: 'Lion-Heart',
    emoji: '🦁',
    pun: 'lion + lionhearted',
    say: 'Lion heart',
    voice: { pitch: 0.7, rate: 0.95 },
    win: 'Brave to the very end!',
    color: '#e0a23a',
    hp: 108,
    speed: 1.0,
    power: 1.05,
    jump: 1,
    special: { type: 'projectile', name: 'Roar Blast', dmg: 15, speed: 520, emoji: '🔥', size: 44 },
  },
  {
    key: 'bearknuckle',
    name: 'Bear-knuckle',
    emoji: '🐻',
    pun: 'bear + bare-knuckle',
    say: 'Bear knuckle',
    voice: { pitch: 0.4, rate: 0.85 },
    win: 'Bear with me. You lost!',
    color: '#8a5a32',
    hp: 112,
    speed: 0.92,
    power: 1.05,
    jump: 0.9,
    special: { type: 'dash', name: 'Knuckle Rush', dmg: 16, speed: 680 },
  },
  {
    key: 'beestmode',
    name: 'Bee-st Mode',
    emoji: '🐝',
    pun: 'bee + beast mode',
    say: 'Beast mode',
    voice: { pitch: 2.0, rate: 1.4 },
    win: 'Bee-st mode, activated!',
    color: '#f2c40c',
    hp: 100,
    speed: 1.3,
    power: 1.1,
    jump: 1.25,
    special: { type: 'projectile', name: 'Stinger Shot', dmg: 12, speed: 780, emoji: '⚡', size: 32 },
  },
  {
    key: 'kickahorse',
    name: 'Kick-a-horse',
    emoji: '🐴',
    pun: 'kick + horse',
    say: 'Kick a horse',
    voice: { pitch: 1.2, rate: 1.15 },
    win: 'Neigh-body beats me!',
    color: '#a86a3d',
    hp: 104,
    speed: 1.15,
    power: 1.02,
    jump: 1.1,
    special: { type: 'dash', name: 'Gallop Kick', dmg: 15, speed: 820 },
  },
  {
    key: 'sharkitecture',
    name: 'Shark-itecture',
    emoji: '🦈',
    pun: 'shark + architecture',
    say: 'Sharkitecture',
    voice: { pitch: 0.8, rate: 1.0 },
    win: 'I built this victory!',
    color: '#5a8ab8',
    hp: 108,
    speed: 1.0,
    power: 1.05,
    jump: 0.95,
    special: { type: 'projectile', name: 'Tidal Wave', dmg: 16, speed: 380, emoji: '🌊', size: 58 },
  },
  {
    key: 'duckandcover',
    name: 'Duck and Cover',
    emoji: '🦆',
    pun: 'duck + fighting phrase',
    say: 'Duck and cover',
    voice: { pitch: 1.7, rate: 1.25 },
    win: 'You should have ducked!',
    color: '#6b8f3a',
    hp: 104,
    speed: 1.15,
    power: 1.02,
    jump: 1.15,
    special: { type: 'projectile', name: 'Egg Grenade', dmg: 15, speed: 560, emoji: '🥚', size: 36 },
  },
  {
    key: 'hissterical',
    name: 'Hiss-terical',
    emoji: '🐍',
    pun: 'hiss + hysterical',
    say: 'Hiss terical',
    voice: { pitch: 1.4, rate: 0.9 },
    win: 'Hisss-terical!',
    color: '#4aa84a',
    hp: 102,
    speed: 1.2,
    power: 1.03,
    jump: 0.95,
    special: { type: 'projectile', name: 'Venom Spit', dmg: 13, speed: 700, emoji: '🟢', size: 26 },
  },
  {
    key: 'crabbat',
    name: 'Crab-bat',
    emoji: '🦀',
    pun: 'crab + combat',
    say: 'Crab bat',
    voice: { pitch: 1.5, rate: 1.2 },
    win: "Don't be so crabby!",
    color: '#e0503a',
    hp: 108,
    speed: 0.9,
    power: 1.0,
    jump: 0.9,
    special: { type: 'uppercut', name: 'Claw Snap', dmg: 13 },
  },
  {
    key: 'octopunch',
    name: 'Octo-Punch',
    emoji: '🐙',
    pun: 'octopus + punch',
    say: 'Octo punch',
    voice: { pitch: 1.3, rate: 1.1 },
    win: 'Eight arms. Zero mercy!',
    color: '#d0508a',
    hp: 106,
    speed: 1.0,
    power: 1.05,
    jump: 1,
    special: { type: 'projectile', name: 'Ink Blast', dmg: 15, speed: 560, emoji: '⚫', size: 36 },
  },
  {
    key: 'gorillawarfare',
    name: 'Gorilla Warfare',
    emoji: '🦍',
    pun: 'gorilla + guerrilla warfare',
    say: 'Gorilla warfare',
    voice: { pitch: 0.3, rate: 0.8 },
    win: 'Ape-solutely crushed!',
    color: '#4a4a55',
    hp: 120,
    speed: 0.95,
    power: 1.08,
    jump: 0.95,
    special: { type: 'slam', name: 'Ground Pound', dmg: 19, radius: 210 },
  },
  {
    key: 'goatnglory',
    name: 'Goat-n Glory',
    emoji: '🐐',
    pun: 'goat + glory',
    say: 'Goat and glory',
    voice: { pitch: 1.0, rate: 1.05 },
    win: 'Greatest of all time!',
    color: '#cfc4a8',
    hp: 104,
    speed: 1.05,
    power: 1.0,
    jump: 1.2,
    special: { type: 'uppercut', name: 'Horn Launcher', dmg: 13 },
  },
  {
    key: 'wolfpack',
    name: 'Wolf Pack',
    emoji: '🐺',
    pun: 'wolf + pack',
    say: 'Wolf pack',
    voice: { pitch: 0.6, rate: 0.95 },
    win: 'Awoooooo!',
    color: '#7a8494',
    hp: 106,
    speed: 1.15,
    power: 1.05,
    jump: 1.05,
    special: { type: 'projectile', name: 'Call the Pack', dmg: 17, speed: 600, emoji: '🐺', size: 48 },
  },
  {
    key: 'rhinomite',
    name: 'Rhino-Mite',
    emoji: '🦏',
    pun: 'rhino + dynamite',
    say: 'Rhino mite',
    voice: { pitch: 0.35, rate: 0.9 },
    win: 'Kaboom! Rhino-mite!',
    color: '#8f8f9c',
    hp: 115,
    speed: 0.85,
    power: 1.05,
    jump: 0.8,
    special: { type: 'dash', name: 'Dynamite Charge', dmg: 17, speed: 760 },
  },
  {
    key: 'frogment',
    name: 'Frog-ment',
    emoji: '🐸',
    pun: 'frog + fragment',
    say: 'Frog ment',
    voice: { pitch: 1.6, rate: 1.2 },
    win: 'Toad-ally smashed!',
    color: '#6cc24a',
    hp: 100,
    speed: 1.1,
    power: 1.0,
    jump: 1.3,
    special: { type: 'uppercut', name: 'Leap Frog', dmg: 14 },
  },
]
