// All 1,001 achievements. Each one is [name, description, statKey, amount, hidden?].
// An achievement unlocks when stat(statKey) >= amount. `ach` is the number of
// other achievements already unlocked; list-based stats are counted from the save.
import { COSTUMES } from './costumes'

export const TOTAL_SECRETS = 22
export const PRESET_MAP_COUNT = 12
export const CHALLENGE_TYPES = 20
export const EVENT_TYPES = 24
const ALL_COSTUMES = Object.keys(COSTUMES).length

const q = (n, name) => [name || `Achievement ${n}`, `Quack ${n} times. (Press Q!)`, 'quacks', n]

const LIST = [
  // 🌱 Beginner 1–50
  ['First Steps', 'Play your first match.', 'matches', 1],
  ['Welcome In', 'Enter the game.', 'welcome', 1],
  ['First Jump', 'Jump for the first time.', 'jumps', 1],
  ['First Knockout', 'Knock out your first duck.', 'kos', 1],
  ['First Win', 'Win your first match.', 'wins', 1],
  ['First Loss', 'Lose your first match.', 'losses', 1],
  ['Bouncy', 'Jump 10 times.', 'jumps', 10],
  ['Getting Started', 'Play 5 matches.', 'matches', 5],
  ['Rookie', 'Play 10 matches.', 'matches', 10],
  ['Regular', 'Play 25 matches.', 'matches', 25],
  ['Newbie No More', 'Play 50 matches.', 'matches', 50],
  ['Participant', 'Finish a match.', 'finished', 1],
  ['Survivor', 'Survive for 30 seconds in a match.', 'best_survive', 30],
  ['Tiny Victory', 'Win a match with 4 or fewer ducks.', 'winsSmall', 1],
  ['Big Victory', 'Win a match with 10 ducks.', 'winsBig', 1],
  ['Oops', 'Fall off the arena.', 'falls', 1],
  ['Again!', 'Play another match after losing.', 'again', 1],
  ['One More', 'Play three matches in a row.', 'best_playStreak', 3],
  ['Jumper', 'Jump 100 times.', 'jumps', 100],
  ['Bouncer', 'Jump 500 times.', 'jumps', 500],
  ['Bonk', 'Get hit for the first time.', 'hitsTaken', 1],
  ['Bonk Back', 'Knock out someone who hit you.', 'revengeKos', 1],
  ['Safe Landing', 'Land safely after being launched high.', 'bigLandings', 1],
  ['Close Call', 'Survive 20 seconds on your last balloon.', 'best_lastBalloon', 20],
  ['Lucky', 'Get launched far and still land on the arena.', 'luckyLandings', 1],
  ['Explorer', 'Visit 5 arenas.', 'maps', 5],
  ['Tourist', 'Visit 10 arenas.', 'maps', 10],
  ['Arena Hopper', 'Visit 25 arenas.', 'maps', 25],
  ['Fighter', 'Get 10 knockouts.', 'kos', 10],
  ['Brawler', 'Get 25 knockouts.', 'kos', 25],
  ['Bruiser', 'Get 50 knockouts.', 'kos', 50],
  ['Champion', 'Win 10 matches.', 'wins', 10],
  ['Superstar', 'Win 25 matches.', 'wins', 25],
  ['Legend', 'Win 50 matches.', 'wins', 50],
  ['Veteran', 'Play 100 matches.', 'matches', 100],
  ['Dedicated', 'Play 250 matches.', 'matches', 250],
  ['Addicted', 'Play 500 matches.', 'matches', 500],
  ['Here We Go', 'Start 10 matches.', 'matchesStarted', 10],
  ['Ready!', 'Start 50 matches.', 'matchesStarted', 50],
  ['Fight!', 'Start 100 matches.', 'matchesStarted', 100],
  ['Still Standing', 'Survive a full minute in a match.', 'best_survive', 60],
  ["Can't Catch Me", 'Dash away from an attack.', 'dashDodges', 1],
  ['Up High', 'Reach the top of the hub tower.', 'roofTop', 1],
  ['Down Low', 'Find the lowest platform in the hub.', 'lowPlatform', 1],
  ['Side Step', 'Dodge an attack.', 'dodges', 1],
  ['Skybound', 'Spend 10 seconds airborne in one match.', 'best_airTotal', 10],
  ['Landing Expert', 'Land 50 jumps.', 'landings', 50],
  ['Air Time', 'Spend 60 seconds in the air in total.', 'airtime', 60],
  ['Grounded', 'Win without jumping.', 'winsNoJump', 1],
  ['Welcome to the Chaos', 'Finish a match with 3 or more events.', 'chaosMatches', 1],

  // 💥 Knockouts 51–100
  ['Bonk Master', 'Get 100 knockouts.', 'kos', 100],
  ['Knockout King', 'Get 250 knockouts.', 'kos', 250],
  ['Knockout Machine', 'Get 500 knockouts.', 'kos', 500],
  ['Knockout Legend', 'Get 1,000 knockouts.', 'kos', 1000],
  ['Double Bonk', 'Knock out two ducks within 4 seconds.', 'multi2', 1],
  ['Triple Bonk', 'Knock out three ducks within 4 seconds each.', 'multi3', 1],
  ['Quad Bonk', 'Knock out four ducks within 4 seconds each.', 'multi4', 1],
  ['Chain Reaction', 'Knock out 5 ducks in one match.', 'best_kos', 5],
  ['Mega Bonk', 'Knock someone out with a mega, golden or king hit.', 'megaKos', 1],
  ['Air Bonk', 'Knock someone out while you are airborne.', 'airKos', 1],
  ['Jump Bonk', 'Knock someone out right after jumping.', 'jumpKos', 1],
  ['Ground Bonk', 'Knock someone out while standing on the ground.', 'groundKos', 1],
  ['Revenge Bonk', 'Knock out 3 ducks who hit you.', 'revengeKos', 3],
  ['Sneaky Bonk', 'Knock someone out from behind.', 'behindKos', 1],
  ['Long Shot', 'Knock someone out from far away.', 'longKos', 1],
  ['Point Blank', 'Knock someone out from very close.', 'closeKos', 1],
  ['Edge Lord', 'Knock out a duck standing near the edge.', 'edgeKos', 1],
  ['Last Second', 'Get a knockout while on your last balloon.', 'lastBalloonKos', 1],
  ['First Blood', 'Get the first knockout of a match.', 'firstBlood', 1],
  ['Final Blow', 'Get the knockout that wins the match.', 'finalBlow', 1],
  ['Steal the KO', "Finish off a duck someone else just hit.", 'stealKos', 1],
  ['KO Collector', 'Knock out three different ducks in one match.', 'best_uniqueKos', 3],
  ['KO Frenzy', 'Get 10 knockouts in one session.', 'best_sessionKos', 10],
  ['KO Storm', 'Get 15 knockouts in one session.', 'best_sessionKos', 15],
  ['KO Tsunami', 'Get 20 knockouts in one session.', 'best_sessionKos', 20],
  ['Bonk Bonk Bonk', 'Get three knockouts without losing a balloon.', 'best_koNoHit', 3],
  ['Bonk-a-Thon', 'Get 25 knockouts in one session.', 'best_sessionKos', 25],
  ['No Mercy', 'Get 5 knockouts in a row without being knocked out.', 'best_koNoOut', 5],
  ['Untouchable', 'Get 10 knockouts without being hit.', 'best_koNoHit', 10],
  ['Perfect Fight', 'Win without losing a single balloon.', 'winsFlawless', 1],
  ['Air Assassin', 'Get 10 airborne knockouts.', 'airKos', 10],
  ['Jumping Menace', 'Get 25 jump knockouts.', 'jumpKos', 25],
  ['Falling Star', 'Knock someone out while you are both in the air.', 'skyKos', 1],
  ['Sky Fight', 'Hit someone while you are both in the air.', 'skyHits', 1],
  ['Wallop', 'Deliver a huge hit.', 'bigHits', 1],
  ['Ouch', 'Pop two balloons with one hit.', 'doublePops', 1],
  ['Tiny Bonk', 'Get a knockout during TINY BONK.', 'tinyKos', 1],
  ['Giant Bonk', 'Get a knockout during GIANT BONK.', 'giantKos', 1],
  ['Double Trouble', 'Hit two ducks with one swing.', 'multiHit2', 1],
  ['Triple Trouble', 'Hit three ducks with one swing.', 'multiHit3', 1],
  ['Bowling Ball', 'Dash into 3 ducks in one match.', 'best_dashBumps', 3],
  ['Pinball', 'Hit a duck that is already flying.', 'airHits', 1],
  ['Boomerang', 'Launch a duck far and watch them land back on the arena.', 'boomerangs', 1],
  ['Goodbye', 'Send an opponent flying off the screen.', 'spaceKos', 1],
  ['See Ya', 'Knock someone out while you stand at the edge.', 'edgeStandKos', 1],
  ['YEET', 'Launch someone extremely far.', 'yeets', 1],
  ['YEET²', 'Launch 2 ducks extremely far.', 'yeets', 2],
  ['YEET³', 'Launch 3 ducks extremely far.', 'yeets', 3],
  ['YEET MASTER', 'Launch 5 ducks extremely far.', 'yeets', 5],
  ['The Bonkening', 'Launch 3 ducks into space.', 'spaceKos', 3],

  // 🦘 Jumps 101–150
  ['Hop!', 'Jump in the hub.', 'hubJumps', 1],
  ['Hop Hop!', 'Jump twice in a row.', 'best_chainJumps', 2],
  ['Hop Hop Hop!', 'Jump three times in a row.', 'best_chainJumps', 3],
  ['Jump Around', 'Jump 1,000 times.', 'jumps', 1000],
  ['Mega Jumper', 'Jump 5,000 times.', 'jumps', 5000],
  ['Jump Legend', 'Jump 10,000 times.', 'jumps', 10000],
  ['Moon Jump', 'Get 250 high in the air.', 'best_height', 250],
  ['Double Jump', 'Jump again in mid-air.', 'flaps', 1],
  ['Triple Jump', 'Jump three times before landing.', 'best_airJumps', 3],
  ['Airborne', 'Stay in the air for 5 seconds.', 'best_air', 5],
  ['Floating', 'Stay in the air for 10 seconds.', 'best_air', 10],
  ['Human Rocket', 'Get launched upward by a bounce pad or bouncy floor.', 'rockets', 1],
  ['Sky Walker', 'Travel 500 across the arena in one flight.', 'best_airDist', 500],
  ['No Ground Needed', 'Stay in the air for 30 seconds.', 'best_air', 30],
  ['Jump Escape', 'Jump over an attack.', 'jumpDodges', 1],
  ['Jump Dodge', 'Jump over 5 attacks.', 'jumpDodges', 5],
  ['Jump Attack', 'Hit someone while you are in the air.', 'airSwingHits', 1],
  ['Jump Defender', 'Block an attack with your shield while airborne.', 'airBlocks', 1],
  ['High Five', 'Hit 3 ducks while you are both in the air.', 'skyHits', 3],
  ['Air Traffic', 'Have 5 ducks in the air at the same time.', 'best_airborneCount', 5],
  ['Sky Party', 'Have 10 ducks in the air at the same time.', 'best_airborneCount', 10],
  ['Ceiling Fan', 'Get 400 high in the air.', 'best_height', 400],
  ['Roof Hopper', 'Land on the hub tower roof 3 times.', 'roofTop', 3],
  ['Bottom Bouncer', 'Use the basement bounce pad to reach the sky.', 'bottomBounce', 1],
  ['Frog Legs', 'Jump 100 times in one match.', 'best_jumps', 100],
  ['Kangaroo Mode', 'Jump 250 times in one match.', 'best_jumps', 250],
  ['Grasshopper', 'Jump 20 times in a row.', 'best_chainJumps', 20],
  ['Boing!', 'Bounce 50 times.', 'bounces', 50],
  ['Boing Boing', 'Bounce 100 times.', 'bounces', 100],
  ['BOING', 'Bounce 500 times.', 'bounces', 500],
  ['Jump Scare', 'Jump right over another duck.', 'jumpOvers', 1],
  ['Leap of Faith', 'Jump across a gap.', 'gapJumps', 1],
  ['Tiny Leap', 'Jump during TINY BONK.', 'tinyJumps', 1],
  ['Giant Leap', 'Jump during GIANT BONK.', 'giantJumps', 1],
  ['Backflip', 'Do the flip emote (press 4).', 'emote_flip', 1],
  ['Frontflip', 'Dash in mid-air.', 'airDashes', 1],
  ['Spin Jump', 'Do the spin emote in mid-air.', 'airSpins', 1],
  ['Stylish Landing', 'Land right after an air trick.', 'styleLandings', 1],
  ['Perfect Landing', 'Land on a moving platform.', 'moverLandings', 1],
  ['Edge Landing', 'Land right at the edge of the arena.', 'edgeLandings', 1],
  ['Lucky Landing', 'Survive 5 huge launches.', 'luckyLandings', 5],
  ['Impossible Landing', 'Land after flying off the screen.', 'impossibleLandings', 1],
  ['Jump Master', 'Reach 50 obby checkpoints.', 'checkpoints', 50],
  ['Jump Scientist', 'Discover the secret obby shortcut.', 'secret_route', 1],
  ['Jump Puzzle', 'Complete the Easy obby.', 'obby_easy', 1],
  ['Parkour Kid', 'Complete the Medium obby.', 'obby_medium', 1],
  ['Parkour Master', 'Complete the Hard obby.', 'obby_hard', 1],
  ['Air Dancer', 'Do 5 emotes in mid-air.', 'airEmotes', 5],
  ['Sky Ninja', 'Jump over 15 attacks.', 'jumpDodges', 15],
  ['The Floor Is Lava', 'Stay in the air for 20 seconds.', 'best_air', 20],

  // 🏃 Movement 151–200
  ['Speedy', 'Dash 10 times.', 'dashes', 10],
  ['Fast Feet', 'Dash 100 times.', 'dashes', 100],
  ['Gotta Go Fast', 'Zoom around for 20 seconds during SUPER SPEED.', 'speedTime', 20],
  ['Blur', 'Dash 500 times.', 'dashes', 500],
  ['Lightning', 'Dash 3 times within 5 seconds.', 'dashBurst', 1],
  ['Human Speed Boost', 'Get a speed boost from a Mystery Box.', 'pu_speed', 1],
  ['Marathon', 'Travel 100,000 in total.', 'distance', 100000],
  ['Sprinter', 'Travel 10,000 in total.', 'distance', 10000],
  ['Runner', 'Travel 1,000 in total.', 'distance', 1000],
  ['Long Distance', 'Travel 50,000 in total.', 'distance', 50000],
  ['Walk It Off', 'Get hit 10 times.', 'hitsTaken', 10],
  ['Sideways', 'Walk only left or right for 5 seconds.', 'sideways', 1],
  ['Lefty', 'Walk left for 5 seconds straight.', 'lefty', 1],
  ['Righty', 'Walk right for 5 seconds straight.', 'righty', 1],
  ['Backwards', 'Walk down for 5 seconds straight.', 'downward', 1],
  ['Backpedal', 'Walk up for 5 seconds straight.', 'upward', 1],
  ['Circle Around', 'Run in a full circle.', 'circles', 1],
  ['Around the World', 'Run in 10 circles.', 'circles', 10],
  ['Dizzy', 'Run in 50 circles.', 'circles', 50],
  ['Spin Doctor', 'Do the spin emote 10 times.', 'spins', 10],
  ['Twirl', 'Do the spin emote (press 2).', 'spins', 1],
  ['Tornado', 'Do the spin emote 50 times.', 'spins', 50],
  ["Don't Stop Moving", 'Keep moving for 30 seconds.', 'best_moveStreak', 30],
  ['Constant Motion', 'Keep moving for 60 seconds.', 'best_moveStreak', 60],
  ['Never Still', 'Keep moving for 2 minutes.', 'best_moveStreak', 120],
  ['Motion Sickness', 'Run in 100 circles.', 'circles', 100],
  ['Zigzag', 'Change direction 10 times in 5 seconds.', 'zigzags', 1],
  ['Wiggly', 'Zigzag 10 times.', 'zigzags', 10],
  ['Slippery', 'Play during SLIPPERY FLOOR.', 'ev_ice', 1],
  ['Escape Artist', 'Dash away from 10 attacks.', 'dashDodges', 10],
  ['Narrow Escape', 'Survive 30 seconds on your last balloon.', 'best_lastBalloon', 30],
  ['Last-Frame Escape', 'Dash away from 3 attacks.', 'dashDodges', 3],
  ['Dodger', 'Dodge 10 attacks.', 'dodges', 10],
  ['Dodge Master', 'Dodge 200 attacks.', 'dodges', 200],
  ['Dodge Legend', 'Dodge 500 attacks.', 'dodges', 500],
  ['Perfect Dodge', 'Dodge 5 attacks in one match.', 'best_dodges', 5],
  ['Ten Dodges', 'Dodge 10 attacks in one match.', 'best_dodges', 10],
  ['Fifty Dodges', 'Dodge 50 attacks.', 'dodges', 50],
  ['Hundred Dodges', 'Dodge 100 attacks.', 'dodges', 100],
  ['Untouchable', 'Finish a match without being hit.', 'noHitMatches', 1],
  ['Ghost', 'Play a match as the Ghost.', 'matchesAs_ghost', 1],
  ['Vanish', 'Play a match with the Invisible Costume.', 'matchesAs_invisible', 1],
  ["Where'd You Go?", 'Fly off the screen and come back.', 'impossibleLandings', 1],
  ['Behind You', 'Hit a duck from behind.', 'behindHits', 1],
  ['Peekaboo', 'Use your shield 25 times.', 'shields', 25],
  ['Around the Corner', 'Ride a moving platform 10 times.', 'rides', 10],
  ['Corner Master', 'Ride moving platforms 50 times.', 'rides', 50],
  ['Wall Runner', 'Run 5,000 in the hub.', 'hubDistance', 5000],
  ['Platform Hopper', 'Reach 10 obby checkpoints.', 'checkpoints', 10],
  ['Movement Master', 'Travel 250,000 in total.', 'distance', 250000],

  // 👑 Victory 201–250
  ['Winner!', 'Win a match.', 'wins', 1],
  ['Big Winner', 'Win 5 matches.', 'wins', 5],
  ['Champion', 'Win 20 matches.', 'wins', 20],
  ['Double Champion', 'Win 2 matches in a row.', 'bestWinStreak', 2],
  ['Triple Champion', 'Win 3 matches in a row.', 'bestWinStreak', 3],
  ['Winning Streak', 'Win 4 matches in a row.', 'bestWinStreak', 4],
  ['Five in a Row', 'Win 5 matches in a row.', 'bestWinStreak', 5],
  ['Ten in a Row', 'Win 10 matches in a row.', 'bestWinStreak', 10],
  ['Twenty in a Row', 'Win 20 matches in a row.', 'bestWinStreak', 20],
  ['Fifty in a Row', 'Win 50 matches in a row.', 'bestWinStreak', 50],
  ['Hundred in a Row', 'Win 100 matches in a row.', 'bestWinStreak', 100],
  ['Comeback Kid', 'Win after being down to your last balloon.', 'comebacks', 1],
  ['Comeback King', 'Make 10 comebacks.', 'comebacks', 10],
  ['Last Survivor', 'Win a match with 8 or more ducks.', 'winsBig8', 1],
  ['Final Player', 'Win 5 matches with 10 ducks.', 'winsBig', 5],
  ['Victory From Nothing', 'Win with no knockouts on your last balloon.', 'winsNothing', 1],
  ['Barely Won', 'Win with only one balloon left.', 'winsLastBalloon', 1],
  ['Perfect Victory', 'Win 3 matches without losing a balloon.', 'winsFlawless', 3],
  ['Speed Winner', 'Win in under 60 seconds.', 'winsFast', 1],
  ['Fastest Victory', 'Win in under 30 seconds.', 'winsVeryFast', 1],
  ['Slow and Steady', 'Win a match that lasts over 3 minutes.', 'winsSlow', 1],
  ['No Jump Victory', 'Win 5 matches without jumping.', 'winsNoJump', 5],
  ['Jump Victory', 'Win after jumping 50 times in the match.', 'winsJumpy', 1],
  ['Air Victory', 'Win while you are in the air.', 'winsAir', 1],
  ['Knockout Victory', 'Win with at least one knockout.', 'winsKo1', 1],
  ['Zero KO Victory', 'Win without knocking anyone out.', 'winsZeroKo', 1],
  ['One KO Victory', 'Win with exactly one knockout.', 'winsOneKo', 1],
  ['Five KO Victory', 'Win with 5 knockouts.', 'winsKo5', 1],
  ['Ten KO Victory', 'Win after knocking out every other duck in a 10-duck match.', 'winsKo9', 1],
  ['Twenty KO Victory', 'Win 20 matches with at least one knockout.', 'winsKo1', 20],
  ['Fifty KO Victory', 'Win 50 matches with at least one knockout.', 'winsKo1', 50],
  ['Arena Champion', 'Win on 3 different arenas.', 'winMaps', 3],
  ['All-Rounder', 'Win on 10 different arenas.', 'winMaps', 10],
  ['Veteran Winner', 'Win 100 matches.', 'wins', 100],
  ['Lucky Winner', 'Win during a rare event.', 'winsRare', 1],
  ['Unlucky Winner', 'Win after falling off twice.', 'winsClumsy', 1],
  ['Last Second Win', 'Win because the last duck fell off by itself.', 'winsSelfDestruct', 1],
  ['Sudden Victory', 'Win during MEGA BONK STORM.', 'winsStorm', 1],
  ['Impossible Victory', 'Win during BONK APOCALYPSE.', 'winsApocalypse', 1],
  ['Secret Victory', 'Win a match the giant rubber duck visited.', 'winsDuck', 1],
  ['Flawless', 'Win 10 matches without losing a balloon.', 'winsFlawless', 10],
  ['Untouched Winner', 'Win without getting hit at all.', 'winsNoHit', 1],
  ['Comeback Champion', 'Make 25 comebacks.', 'comebacks', 25],
  ['Survivor Champion', 'Win 10 matches with 8 or more ducks.', 'winsBig8', 10],
  ['Airborne Champion', 'Win 5 times while in the air.', 'winsAir', 5],
  ['Jump Champion', 'Win 10 jumpy matches.', 'winsJumpy', 10],
  ['Dodge Champion', 'Win after dodging 5 attacks in the match.', 'winsDodgy', 1],
  ['Bonk Champion', 'Win 5 matches with 5 knockouts.', 'winsKo5', 5],
  ['Ultimate Winner', 'Win 500 matches.', 'wins', 500],
  ['You Did It!', 'Win 1,000 matches.', 'wins', 1000],

  // 😂 Funny 251–350
  ['Oops.', 'Fall off 5 times.', 'falls', 5],
  ['OOPS.', 'Fall off 25 times.', 'falls', 25],
  ['OOOOOOPS.', 'Fall off 100 times.', 'falls', 100],
  ['Bonk.', 'Get hit 10 times.', 'hitsTaken', 10],
  ['BONK.', 'Get hit 100 times.', 'hitsTaken', 100],
  ['BONK BONK.', 'Get hit 500 times.', 'hitsTaken', 500],
  ['Why Did I Jump?', 'Jump straight off the edge.', 'jumpFalls', 1],
  ['Wrong Way', 'Dash straight off the edge.', 'dashFalls', 1],
  ['I Meant To Do That', 'Fall off in the first 5 seconds.', 'earlyFalls', 1],
  ['Totally Planned', 'Fall off 3 times in one match.', 'best_falls', 3],
  ['Trust Me', 'Fall off with your shield up.', 'shieldFalls', 1],
  ["Don't Look Down", 'Stand at the very edge for 3 seconds.', 'edgeStand', 1],
  ['I Looked Down', 'Fall off 10 times.', 'falls', 10],
  ['Gravity Wins', 'Fall off 50 times.', 'falls', 50],
  ['Gravity Is Rude', 'Fall off during LOW GRAVITY.', 'lowgravFalls', 1],
  ['Floor Enjoyer', 'Lie on the floor (press 5).', 'flops', 1],
  ['Ceiling Enjoyer', 'Get 300 high in the air.', 'best_height', 300],
  ['Wall Enjoyer', 'Bump into the hub walls 10 times.', 'wallBumps', 10],
  ['Corner Enjoyer', 'Find the hub corner nobody visits.', 'hubCorner', 1],
  ['Professional Loaf', 'Stand still for 30 seconds in the hub.', 'best_idle', 30],
  ['Doing Nothing', 'Stand still for 60 seconds in the hub.', 'best_idle', 60],
  ['Still Loading', 'Watch the loading screen.', 'loadings', 1],
  ['Buffering…', 'Wait 10 seconds on the title screen.', 'buffering', 1],
  ['Connection Lost', 'Try to play online.', 'online', 1],
  ['Brain.exe Stopped', 'Stand still for 10 seconds in a match.', 'matchIdle', 1],
  ['Potato', 'Play a match as the Potato.', 'matchesAs_potato', 1],
  ['Certified Potato', 'Win as the Potato.', 'winsAs_potato', 1],
  ['Mega Potato', 'Win 10 times as the Potato.', 'winsAs_potato', 10],
  ['Flying Potato', 'Get launched while dressed as a Potato.', 'potatoYeets', 1],
  ['Potato Cannon', 'Bonk someone while dressed as a Potato.', 'potatoHits', 1],
  ['BONK Simulator', 'Swing your hammer 1,000 times.', 'swings', 1000],
  ['Get Bonked', 'Get hit 50 times.', 'hitsTaken', 50],
  ['Bonk Yourself', 'Fall off without anyone touching you.', 'selfFalls', 1],
  ['How?', 'Land after flying off the screen.', 'impossibleLandings', 1],
  ['HOW?!', 'Win 3 times on your last balloon.', 'winsLastBalloon', 3],
  ['WHAT?!', 'See the giant rubber duck.', 'ev_duck', 1],
  ['Excuse Me?', 'Get stomped by the giant rubber duck.', 'duckHits', 1],
  ['Did That Just Happen?', 'See a rare event.', 'rareEvents', 1],
  ['Okay Then', 'See 5 rare events.', 'rareEvents', 5],
  ['Nice.', 'Quack 10 times.', 'quacks', 10],
  ['Very Nice.', 'Quack 50 times.', 'quacks', 50],
  ['Extremely Nice.', 'Quack 200 times.', 'quacks', 200],
  ['Not Nice.', 'Bonk a duck while it is doing an emote.', 'emoteHits', 1],
  ['Uh Oh', 'Get down to your last balloon.', 'lastBalloons', 1],
  ['Oh No', 'Get down to your last balloon 10 times.', 'lastBalloons', 10],
  ['Oh NO', 'Lose all your balloons.', 'outs', 1],
  ['NOOOOO', 'Lose all your balloons 25 times.', 'outs', 25],
  ['Goodbye', 'Get launched into space.', 'spaced', 1],
  ['Bye!', 'Get launched into space 5 times.', 'spaced', 5],
  ['Bye Bye!', 'Get launched into space 25 times.', 'spaced', 25],
  ['See Ya!', 'Launch 5 ducks into space.', 'spaceKos', 5],
  ['Where Am I?', 'Fly off the screen.', 'offscreen', 1],
  ['Where Are You?', 'Fly off the screen 10 times.', 'offscreen', 10],
  ['I Lost Myself', 'Fall off the hub island.', 'hubFalls', 1],
  ['Found Myself', 'Fall off the hub island 5 times.', 'hubFalls', 5],
  ['Lost Again', 'Fall off the hub island 20 times.', 'hubFalls', 20],
  ['Jumping for No Reason', 'Jump 20 times in the hub.', 'hubJumps', 20],
  ['Running for No Reason', 'Run 2,000 in the hub.', 'hubDistance', 2000],
  ['Spinning for No Reason', 'Spin 5 times in the hub.', 'hubSpins', 5],
  ['Standing for No Reason', 'Stand still for 2 minutes in the hub.', 'best_idle', 120],
  ['Professional Button Presser', 'Press 100 buttons.', 'buttons', 100],
  ['Press Everything', 'Press 500 buttons.', 'buttons', 500],
  ["Don't Press That", 'Press the big red button in the hub.', 'redButton', 1],
  ['You Pressed It', 'Press the big red button 5 times.', 'redButton', 5],
  ['Why Did You Press It?', 'Press the big red button 25 times.', 'redButton', 25],
  ['Mystery Button', 'Find the secret button.', 'secret_button', 1, true],
  ['Button Goblin', 'Press 1,000 buttons.', 'buttons', 1000],
  ['Button Wizard', 'Press 2,500 buttons.', 'buttons', 2500],
  ['Button Overlord', 'Press 5,000 buttons.', 'buttons', 5000],
  ['Menu Enjoyer', 'Open menus 25 times.', 'menus', 25],
  ['Achievement Enjoyer', 'Open the achievements board 10 times.', 'achViews', 10],
  ['Loading Screen Enjoyer', 'See the loading screen 10 times.', 'loadings', 10],
  ['Settings Enjoyer', 'Change the sound setting 5 times.', 'settings', 5],
  ['Backwards Champion', 'Win without swinging your hammer.', 'winsNoSwing', 1],
  ['Walking Simulator', 'Run 10,000 in the hub.', 'hubDistance', 10000],
  ['Jumping Simulator', 'Jump 500 times in the hub.', 'hubJumps', 500],
  ['Falling Simulator', 'Fall off 250 times.', 'falls', 250],
  ['Gravity Simulator', 'Play during LOW GRAVITY 5 times.', 'ev_lowgrav', 5],
  ['Floor Inspector', 'Lie on the floor 10 times.', 'flops', 10],
  ['Ceiling Inspector', 'Land on the hub tower roof 5 times.', 'roofTop', 5],
  ['Wall Inspector', 'Bump into the hub walls 50 times.', 'wallBumps', 50],
  ['Physics Inspector', 'Get launched 100 times.', 'launched', 100],
  ['Certified Chaos', 'See 25 events.', 'eventsSeen', 25],
  ['Maximum Chaos', 'See 100 events.', 'eventsSeen', 100],
  ['Absolute Chaos', 'See 500 events.', 'eventsSeen', 500],
  ['What Is Happening?', 'See MEGA BONK STORM.', 'ev_storm', 1],
  ['Send Help', 'See BONK APOCALYPSE.', 'ev_apocalypse', 1],
  ['Never Mind', 'Leave a match early.', 'quits', 1],
  ['Everything Is Fine', 'Survive an EARTHQUAKE.', 'survive_quake', 1],
  ['Probably Fine', 'Survive RISING LAVA.', 'survive_lava', 1],
  ['Definitely Fine', 'Survive a METEOR SHOWER.', 'survive_meteors', 1],
  ['Totally Fine', 'Survive THE FLOOR IS GONE.', 'survive_floorgone', 1],
  ['Fine.', 'Survive MEGA BONK STORM.', 'survive_storm', 1],
  ['Fine?!', 'Survive BONK APOCALYPSE.', 'survive_apocalypse', 1],
  ['FINE!!!', 'Survive the giant rubber duck.', 'survive_duck', 1],
  ['Bonk Bonk Bonk Bonk', 'Hit 4 ducks within 4 seconds.', 'fastHits', 1],
  ['Jump Jump Jump', 'Jump 10 times in a row.', 'best_chainJumps', 10],
  ['Run Run Run', 'Travel 20,000 in total.', 'distance', 20000],
  ['Spin Spin Spin', 'Do the spin emote 100 times.', 'spins', 100],
  ['What A Match', 'See 5 events in one match.', 'best_eventsInMatch', 5],

  // 🗺️ Arenas 351–400
  ['Arena Explorer', 'Visit 4 arenas.', 'maps', 4],
  ['Arena Tourist', 'Visit 15 arenas.', 'maps', 15],
  ['First Arena', 'Visit your first arena.', 'maps', 1],
  ['Second Arena', 'Visit 2 arenas.', 'maps', 2],
  ['Third Arena', 'Visit 3 arenas.', 'maps', 3],
  ['Fifth Arena', 'Visit 5 arenas.', 'maps', 5],
  ['Tenth Arena', 'Visit 10 arenas.', 'maps', 10],
  ['Twenty Arenas', 'Visit 20 arenas.', 'maps', 20],
  ['Every Arena', 'Visit every handmade arena.', 'presetsVisited', PRESET_MAP_COUNT],
  ['Arena Collector', 'Visit 30 arenas.', 'maps', 30],
  ['Platform Explorer', 'Ride a moving platform.', 'rides', 1],
  ['Secret Platform', 'Find the secret platform in the hub.', 'secret_platform', 1, true],
  ['Hidden Platform', 'Find the hidden platform in the hub.', 'secret_hidden', 1, true],
  ['Tiny Platform', 'Play on Tiny Island.', 'map_tiny', 1],
  ['Giant Platform', 'Play on Mega Pancake.', 'map_mega', 1],
  ['Moving Platform', 'Ride moving platforms 25 times.', 'rides', 25],
  ['Falling Platform', 'Be standing on a floor tile when it falls.', 'tileFalls', 1],
  ['Bouncy Platform', 'Use a bounce pad in the hub.', 'hubBounces', 1],
  ['Slippery Platform', 'Play during SLIPPERY FLOOR 3 times.', 'ev_ice', 3],
  ['Weird Platform', 'Play on a random blob arena.', 'blobs', 1],
  ['Platform Master', 'Ride moving platforms 200 times.', 'rides', 200],
  ['Platform Legend', 'Ride moving platforms 1,000 times.', 'rides', 1000],
  ['Edge Explorer', 'Stand at the very edge 5 times.', 'edgeStand', 5],
  ['Edge Walker', 'Spend 30 seconds near the edge.', 'edgeTime', 30],
  ['Edge Master', 'Spend 5 minutes near the edge.', 'edgeTime', 300],
  ["Don't Fall", 'Finish a match without falling off.', 'noFallMatches', 1],
  ['Almost Fell', 'Land right at the edge 5 times.', 'edgeLandings', 5],
  ['Fell Anyway', 'Fall off 20 times.', 'falls', 20],
  ['Arena Acrobat', 'Jump 2,500 times.', 'jumps', 2500],
  ['Arena Ninja', 'Finish 5 matches without being hit.', 'noHitMatches', 5],
  ['Arena Speedrunner', 'Win 5 matches in under 60 seconds.', 'winsFast', 5],
  ['Arena Survivor', 'Survive 3 minutes in one match.', 'best_survive', 180],
  ['Arena Champion', 'Win on 5 different arenas.', 'winMaps', 5],
  ['Map Master', 'Visit 25 arenas.', 'maps', 25],
  ['Map Explorer', 'Visit 8 arenas.', 'maps', 8],
  ['Map Completionist', 'Visit 40 arenas.', 'maps', 40],
  ['Secret Map', 'Play on The Void.', 'map_void', 1, true],
  ['Hidden Map', 'Play on Candy Kingdom.', 'map_candy', 1, true],
  ['Strange Map', 'Play on Duck Pond.', 'map_pond', 1, true],
  ['Weird Map', 'Play on 10 blob arenas.', 'blobs', 10],
  ['Tiny Map', 'Win on Tiny Island.', 'winMap_tiny', 1],
  ['Huge Map', 'Win on Mega Pancake.', 'winMap_mega', 1],
  ['Floating Map', 'Play on Island Hop.', 'map_islands', 1],
  ['Sky Map', 'Play on Sky Steps.', 'map_steps', 1],
  ['Underground Map', 'Play a match at night.', 'nightMatches', 1],
  ['Impossible Map', 'Win on The Void.', 'winMap_void', 1, true],
  ['Chaos Map', 'See 3 events in one match.', 'best_eventsInMatch', 3],
  ['Noisy Map', 'Play 10 matches with sound on.', 'soundMatches', 10],
  ['Silent Map', 'Play a match with sound off.', 'mutedMatches', 1],
  ['Arena Legend', 'Visit 48 arenas.', 'maps', 48],

  // 🎯 Challenges 401–450
  ['Challenge Accepted', 'Start a challenge.', 'chStarted', 1],
  ['Challenge Complete', 'Win a challenge.', 'chWon', 1],
  ['Challenge Master', 'Win 25 challenges.', 'chWon', 25],
  ['Challenge Legend', 'Win 250 challenges.', 'chWon', 250],
  ['Easy Mode', 'Win against Easy bots.', 'win_easy', 1],
  ['Medium Mode', 'Win against Medium bots.', 'win_medium', 1],
  ['Hard Mode', 'Win against Hard bots.', 'win_hard', 1],
  ['Extreme Mode', 'Win against Extreme bots.', 'win_extreme', 1],
  ['Impossible Mode', 'Win against Impossible bots.', 'win_impossible', 1],
  ['No-Jump Challenge', 'Win the No-Jump challenge.', 'ch_nojump', 1],
  ['Jump-Only Challenge', 'Win the Jump-Only challenge.', 'ch_jumponly', 1],
  ['No-Attack Challenge', 'Win the No-Attack challenge.', 'ch_noattack', 1],
  ['No-Damage Challenge', 'Win the No-Damage challenge.', 'ch_nodamage', 1],
  ['One-Life Challenge', 'Win the One-Life challenge.', 'ch_onelife', 1],
  ['Speed Challenge', 'Win the Speed challenge.', 'ch_speed', 1],
  ['Slow Challenge', 'Win the Slow challenge.', 'ch_slow', 1],
  ['Dodge Challenge', 'Win the Dodge challenge.', 'ch_dodge', 1],
  ['Knockout Challenge', 'Win the Knockout challenge.', 'ch_ko', 1],
  ['Survival Challenge', 'Win the Survival challenge.', 'ch_survival', 1],
  ['Air Challenge', 'Win the Air challenge.', 'ch_air', 1],
  ['Platform Challenge', 'Win the Platform challenge.', 'ch_platform', 1],
  ['Edge Challenge', 'Win the Edge challenge.', 'ch_edge', 1],
  ['Tiny Arena Challenge', 'Win the Tiny Arena challenge.', 'ch_tiny', 1],
  ['Giant Arena Challenge', 'Win the Giant Arena challenge.', 'ch_giant', 1],
  ['Ten-KO Challenge', 'Get 10 knockouts in challenges.', 'chKos', 10],
  ['Twenty-KO Challenge', 'Get 20 knockouts in challenges.', 'chKos', 20],
  ['Thirty-KO Challenge', 'Get 30 knockouts in challenges.', 'chKos', 30],
  ['Fifty-KO Challenge', 'Get 50 knockouts in challenges.', 'chKos', 50],
  ['One-Minute Challenge', 'Survive a minute in a challenge.', 'best_chSurvive', 60],
  ['Five-Minute Challenge', 'Play challenges for 5 minutes.', 'chPlaytime', 300],
  ['Ten-Minute Challenge', 'Play challenges for 10 minutes.', 'chPlaytime', 600],
  ['No-Falling Challenge', 'Win a challenge without falling off.', 'chNoFall', 1],
  ['No-Landing Challenge', 'Win the Air challenge twice.', 'ch_air', 2],
  ['Perfect Challenge', 'Win a challenge without losing a balloon.', 'chFlawless', 1],
  ['Lucky Challenge', 'Win a challenge on your last balloon.', 'chLastBalloon', 1],
  ['Secret Challenge', 'Win the secret Duck Hunt challenge.', 'ch_duckhunt', 1, true],
  ['Hidden Challenge', 'Win the hidden Mirror challenge.', 'ch_mirror', 1, true],
  ['Mystery Challenge', 'Win the Mystery challenge.', 'ch_random', 1],
  ['Chaos Challenge', 'Win the Chaos challenge.', 'ch_chaos', 1],
  ['Ultimate Challenge', 'Win the Ultimate challenge.', 'ch_ultimate', 1],
  ['Challenge Chain', 'Win 2 challenges in a row.', 'best_chStreak', 2],
  ['Challenge Streak', 'Win 5 challenges in a row.', 'best_chStreak', 5],
  ['Five Challenges', 'Win 5 challenges.', 'chWon', 5],
  ['Ten Challenges', 'Win 10 challenges.', 'chWon', 10],
  ['Twenty Challenges', 'Win 20 challenges.', 'chWon', 20],
  ['Fifty Challenges', 'Win 50 challenges.', 'chWon', 50],
  ['Hundred Challenges', 'Win 100 challenges.', 'chWon', 100],
  ['Challenge Collector', 'Win 10 different challenges.', 'chTypes', 10],
  ['Challenge Mastermind', 'Win every challenge.', 'chTypes', CHALLENGE_TYPES],
  ['Challenge Overload', 'Start 200 challenges.', 'chStarted', 200],

  // 🔥 Streaks 451–500
  ['Hot Start', 'Get a knockout in the first 10 seconds.', 'earlyKos', 1],
  ['On Fire', 'Get 3 knockouts without being hit.', 'best_koNoHit', 3],
  ['Burning Up', 'Get 5 knockouts without being hit.', 'best_koNoHit', 5],
  ['Unstoppable', 'Get 10 knockouts without being knocked out.', 'best_koNoOut', 10],
  ['Five KOs', 'Get 5 knockouts in a row without being knocked out.', 'best_koNoOut', 5],
  ['Ten KOs', 'Get 10 knockouts in a row without being knocked out.', 'best_koNoOut', 10],
  ['Fifteen KOs', 'Get 15 knockouts in a row without being knocked out.', 'best_koNoOut', 15],
  ['Twenty KOs', 'Get 20 knockouts in a row without being knocked out.', 'best_koNoOut', 20],
  ['Twenty-Five KOs', 'Get 25 knockouts in a row without being knocked out.', 'best_koNoOut', 25],
  ['Thirty KOs', 'Get 30 knockouts in a row without being knocked out.', 'best_koNoOut', 30],
  ['Five Wins', 'Win 5 matches.', 'wins', 5],
  ['Ten Wins', 'Win 10 matches.', 'wins', 10],
  ['Fifteen Wins', 'Win 15 matches.', 'wins', 15],
  ['Twenty Wins', 'Win 20 matches.', 'wins', 20],
  ['Twenty-Five Wins', 'Win 25 matches.', 'wins', 25],
  ['Thirty Wins', 'Win 30 matches.', 'wins', 30],
  ['Five Dodges', 'Dodge 5 attacks in one match.', 'best_dodges', 5],
  ['Ten Dodges', 'Dodge 10 attacks in one match.', 'best_dodges', 10],
  ['Fifteen Dodges', 'Dodge 15 attacks in one match.', 'best_dodges', 15],
  ['Twenty Dodges', 'Dodge 20 attacks in one match.', 'best_dodges', 20],
  ['Five Jumps', 'Jump 5 times in one match.', 'best_jumps', 5],
  ['Ten Jumps', 'Jump 10 times in one match.', 'best_jumps', 10],
  ['Twenty Jumps', 'Jump 20 times in one match.', 'best_jumps', 20],
  ['Fifty Jumps', 'Jump 50 times in one match.', 'best_jumps', 50],
  ['Hundred Jumps', 'Jump 100 times in one match.', 'best_jumps', 100],
  ['Five Matches', 'Play 5 matches in a row.', 'best_playStreak', 5],
  ['Ten Matches', 'Play 10 matches in a row.', 'best_playStreak', 10],
  ['Twenty Matches', 'Play 20 matches in a row.', 'best_playStreak', 20],
  ['Fifty Matches', 'Play 50 matches in a row.', 'best_playStreak', 50],
  ['Hundred Matches', 'Play 100 matches in a row.', 'best_playStreak', 100],
  ['KO Streak', 'Get 3 knockouts in a row without being knocked out.', 'best_koNoOut', 3],
  ['Victory Streak', 'Win 3 in a row.', 'bestWinStreak', 3],
  ['Dodge Streak', 'Dodge 3 attacks in one match.', 'best_dodges', 3],
  ['Jump Streak', 'Jump 5 times in a row.', 'best_chainJumps', 5],
  ['Survival Streak', 'Finish 3 matches in a row without falling off.', 'best_noFallStreak', 3],
  ['Perfect Streak', 'Win 2 flawless matches in a row.', 'best_flawlessStreak', 2],
  ['No-Hit Streak', 'Finish 2 matches in a row without being hit.', 'best_noHitStreak', 2],
  ['No-Fall Streak', 'Finish 5 matches in a row without falling off.', 'best_noFallStreak', 5],
  ['Air Streak', 'Stay in the air for 8 seconds.', 'best_air', 8],
  ['Chaos Streak', 'Survive 5 events in one match.', 'best_eventsSurvived', 5],
  ['Mega Streak', 'Win 7 in a row.', 'bestWinStreak', 7],
  ['Ultra Streak', 'Win 12 in a row.', 'bestWinStreak', 12],
  ['Super Streak', 'Win 15 in a row.', 'bestWinStreak', 15],
  ['Insane Streak', 'Win 25 in a row.', 'bestWinStreak', 25],
  ['Legendary Streak', 'Win 40 in a row.', 'bestWinStreak', 40],
  ['Eternal Streak', 'Win 75 in a row.', 'bestWinStreak', 75],
  ['Streak Machine', 'Get 50 knockouts in a row without being knocked out.', 'best_koNoOut', 50],
  ['Streak Monster', 'Get 75 knockouts in a row without being knocked out.', 'best_koNoOut', 75],
  ['Streak Lord', 'Get 100 knockouts in a row without being knocked out.', 'best_koNoOut', 100],
  ['STREAKAGEDDON', 'Win 150 in a row.', 'bestWinStreak', 150],

  // 👻 Secrets 501–550
  ['???', 'Find a secret.', 'secretsFound', 1, true],
  ['???', 'Find another secret.', 'secretsFound', 2, true],
  ['Behind the Wall', 'Find what is behind the wall.', 'secret_wall', 1, true],
  ['Under the Map', 'Find the place under the hub.', 'secret_under', 1, true],
  ['Above the Map', 'Find the place above the hub.', 'secret_above', 1, true],
  ['Secret Room', 'Find the secret room.', 'secret_room', 1, true],
  ['Secret Door', 'Find the secret door.', 'secret_door', 1, true],
  ['Secret Button', 'Press the secret button.', 'secret_button', 1, true],
  ['Secret Platform', 'Stand on the secret platform.', 'secret_platform', 1, true],
  ['Secret Character', 'Meet Old Quackers.', 'secret_npc', 1, true],
  ['Secret Arena', 'Play on The Void 3 times.', 'voidPlays', 3, true],
  ['Secret Route', 'Take the obby shortcut.', 'secret_route', 1, true],
  ['Secret Ending', 'Find the hidden end of the Hard obby.', 'secret_ending', 1, true],
  ['Hidden Path', 'Walk the hidden path.', 'secret_path', 1, true],
  ['Hidden Button', 'Find the hidden button.', 'secret_button2', 1, true],
  ['Hidden Message', 'Read the hidden message.', 'secret_message', 1, true],
  ['Hidden Room', 'Get inside the tower.', 'secret_room2', 1, true],
  ['Hidden Platform', 'Stand on the hidden platform.', 'secret_hidden', 1, true],
  ['Hidden Character', 'Meet Tiny Quackers.', 'secret_npc2', 1, true],
  ['Hidden Arena', 'Play on Candy Kingdom.', 'map_candy', 1, true],
  ['Mystery Box', 'Open a Mystery Box.', 'mysteryBoxes', 1],
  ['Mystery Switch', 'Flip the mystery switch.', 'secret_switch', 1, true],
  ['Mystery Door', 'Walk through the mystery door.', 'secret_door2', 1, true],
  ['Mystery Place', 'Find the mystery place.', 'secret_place', 1, true],
  ['Mystery Player', 'Play against the mystery duck.', 'mysteryBot', 1, true],
  ['Strange Things', 'See 3 rare events.', 'rareEvents', 3],
  ["Something's Wrong", 'Something has entered the arena.', 'ev_duck', 1, true],
  ["Something's REALLY Wrong", 'It came back. Three times.', 'ev_duck', 3, true],
  ['Glitch?', 'Play a match as the Glitch.', 'matchesAs_glitch', 1],
  ['Definitely a Glitch', 'Play a match as the Golden Glitch.', 'matchesAs_goldenglitch', 1],
  ["That's Not Supposed to Happen", 'Land on the secret cloud.', 'secret_cloud', 1, true],
  ['How Did You Get There?', 'Climb the tall tree.', 'secret_tree', 1, true],
  ['You Found It', 'Find 5 secrets.', 'secretsFound', 5, true],
  ['You Really Found It', 'Find 10 secrets.', 'secretsFound', 10, true],
  ['Nobody Was Supposed to Find This', 'Find 15 secrets.', 'secretsFound', 15, true],
  ["Developer's Secret", 'Find the developer room.', 'secret_dev', 1, true],
  ['Developer Room', 'Use the developer computer.', 'secret_devpc', 1, true],
  ['Debug Master', 'Type BONK in the hub.', 'secret_typed', 1, true],
  ['Out of Bounds', 'Walk to the far edge of the hub.', 'secret_oob', 1, true],
  ['Beyond the Arena', 'Fly off the screen 25 times.', 'offscreen', 25],
  ['Void Walker', 'Fall off the hub island 50 times.', 'hubFalls', 50],
  ['Lost in Space', 'Get launched into space 50 times.', 'spaced', 50],
  ['The Forgotten Platform', 'Find the forgotten platform.', 'secret_forgotten', 1, true],
  ['The Forbidden Jump', 'Jump off the top of the tower into the well.', 'secret_forbidden', 1, true],
  ['The Impossible Jump', 'Finish the Hard obby without a checkpoint.', 'obbyHardNoCp', 1],
  ['The Impossible KO', 'Knock out THE BONK KING.', 'kingKos', 1],
  ['The Impossible Win', 'Win the Ultimate challenge.', 'ch_ultimate', 1],
  ['The Hidden Champion', 'Win while invisible.', 'winsAs_invisible', 1, true],
  ['Secret Master', 'Find 20 secrets.', 'secretsFound', 20, true],
  ['Secret Legend', 'Find every secret.', 'secretsFound', TOTAL_SECRETS, true],

  // 🎮 Gameplay 551–600
  ['First Match', 'Play a match.', 'matches', 1],
  ['Ten Matches', 'Play 10 matches.', 'matches', 10],
  ['Fifty Matches', 'Play 50 matches.', 'matches', 50],
  ['Hundred Matches', 'Play 100 matches.', 'matches', 100],
  ['First KO', 'Get a knockout.', 'kos', 1],
  ['Hundred KOs', 'Get 100 knockouts.', 'kos', 100],
  ['First Jump', 'Jump.', 'jumps', 1],
  ['Thousand Jumps', 'Jump 1,000 times.', 'jumps', 1000],
  ['First Dodge', 'Dodge an attack.', 'dodges', 1],
  ['Hundred Dodges', 'Dodge 100 attacks.', 'dodges', 100],
  ['First Win', 'Win a match.', 'wins', 1],
  ['Hundred Wins', 'Win 100 matches.', 'wins', 100],
  ['First Arena', 'Play on an arena.', 'maps', 1],
  ['All Arenas', 'Play on every handmade arena.', 'presetsVisited', PRESET_MAP_COUNT],
  ['First Challenge', 'Win a challenge.', 'chWon', 1],
  ['All Challenges', 'Win every challenge.', 'chTypes', CHALLENGE_TYPES],
  ['First Secret', 'Find a secret.', 'secretsFound', 1],
  ['All Secrets', 'Find every secret.', 'secretsFound', TOTAL_SECRETS],
  ['First Character', 'Change your costume.', 'costumeChanges', 1],
  ['All Characters', 'Play matches in 20 different costumes.', 'costumesWorn', 20],
  ['First Cosmetic', 'Buy a costume.', 'costumesOwned', 2],
  ['Cosmetic Collector', 'Own 25 costumes.', 'costumesOwned', 25],
  ['First Emote', 'Do an emote (keys 1–5).', 'emotes', 1],
  ['Emote Collector', 'Do all 5 emotes.', 'emoteTypes', 5],
  ['First Victory', 'Win a match.', 'wins', 1],
  ['Victory Collector', 'Win 50 matches.', 'wins', 50],
  ['KO Collector', 'Get 50 knockouts.', 'kos', 50],
  ['Jump Collector', 'Jump 5,000 times.', 'jumps', 5000],
  ['Dodge Collector', 'Dodge 250 attacks.', 'dodges', 250],
  ['Arena Collector', 'Visit 20 arenas.', 'maps', 20],
  ['Challenge Collector', 'Win 10 different challenges.', 'chTypes', 10],
  ['Secret Collector', 'Find 10 secrets.', 'secretsFound', 10],
  ['Achievement Collector', 'Unlock 100 achievements.', 'ach', 100],
  ['Halfway There', 'Unlock 500 achievements.', 'ach', 500],
  ['Almost There', 'Unlock 900 achievements.', 'ach', 900],
  ['Completionist', 'Unlock 600 achievements.', 'ach', 600],
  ['Super Completionist', 'Unlock 700 achievements.', 'ach', 700],
  ['Mega Completionist', 'Unlock 750 achievements.', 'ach', 750],
  ['Ultra Completionist', 'Unlock 800 achievements.', 'ach', 800],
  ['Maximum Completionist', 'Unlock 850 achievements.', 'ach', 850],
  ['Everything Unlocked', 'Own every costume.', 'costumesOwned', ALL_COSTUMES],
  ['Almost Everything', 'Own 75 costumes.', 'costumesOwned', 75],
  ['One More!', 'Play again right after winning.', 'afterWin', 1],
  ['Just One More', 'Play 5 matches in one session.', 'best_sessionMatches', 5],
  ['Again Again!', 'Play 10 matches in one session.', 'best_sessionMatches', 10],
  ["Can't Stop", 'Play 20 matches in one session.', 'best_sessionMatches', 20],
  ['Never Stop', 'Play 50 matches in one session.', 'best_sessionMatches', 50],
  ['Keep Going', 'Play for 1 hour in total.', 'playtime', 3600],
  ['Final Boss', 'Knock out THE BONK KING 3 times.', 'kingKos', 3],
  ['The End…?', 'Win a match the giant rubber duck visited.', 'winsDuck', 1],

  // 🤪 Extremely weird 601–650
  ['Touch Grass', 'Walk on the grass in the hub.', 'grass', 1],
  ['Touch More Grass', 'Spend a minute on the grass.', 'grass', 60],
  ['Become Grass', 'Stand still on the grass for 30 seconds.', 'best_grassIdle', 30],
  ['Grass Champion', 'Spend 10 minutes on the grass.', 'grass', 600],
  ['Become the Floor', 'Lie on the floor.', 'flops', 1],
  ['Floor Boss', 'Lie on the floor 50 times.', 'flops', 50],
  ['Become the Ceiling', 'Get 450 high in the air.', 'best_height', 450],
  ['Ceiling Boss', 'Land on the tower roof 25 times.', 'roofTop', 25],
  ['Become a Wall', 'Stand still against a wall for 10 seconds.', 'wallIdle', 1],
  ['Wall Boss', 'Bump into walls 200 times.', 'wallBumps', 200],
  ['Become a Platform', 'Stand still on a moving platform for 10 seconds.', 'platformIdle', 1],
  ['Platform Boss', 'Ride moving platforms 500 times.', 'rides', 500],
  ['Become Gravity', 'Knock out 3 ducks during LOW GRAVITY.', 'lowgravKos', 3],
  ['Defeat Gravity', 'Stay in the air for 15 seconds.', 'best_air', 15],
  ['Befriend Gravity', 'Play during LOW GRAVITY 10 times.', 'ev_lowgrav', 10],
  ['Anger Gravity', 'Fall off 5 times during LOW GRAVITY.', 'lowgravFalls', 5],
  ['Confuse Gravity', 'Flap in mid-air 100 times.', 'flaps', 100],
  ['Break Gravity', 'Get 600 high in the air.', 'best_height', 600],
  ['Become a Ball', 'Play a match as the Bouncy Ball.', 'matchesAs_ball', 1],
  ['Become a Potato', 'Play a match as the Potato.', 'matchesAs_potato', 1],
  ['Become a Chair', 'Play a match as the Chair.', 'matchesAs_chair', 1],
  ['Become a Chair Again', 'Play 5 matches as the Chair.', 'matchesAs_chair', 5],
  ['Chair Champion', 'Win as the Chair.', 'winsAs_chair', 1],
  ['Defeat a Chair', 'Knock out a duck dressed as a Chair.', 'chairKos', 1],
  ['Fight Nobody', 'Swing at nobody 10 times.', 'airSwings', 10],
  ['Lose to Nobody', 'Fall off 10 times without anyone touching you.', 'selfFalls', 10],
  ['Win Against Nobody', 'Win 3 times because the last duck fell off by itself.', 'winsSelfDestruct', 3],
  ['Jump at Nothing', 'Jump 100 times in the hub.', 'hubJumps', 100],
  ['Punch Nothing', 'Swing at nobody 100 times.', 'airSwings', 100],
  ['Dodge Nothing', 'Dash 50 times in the hub.', 'hubDashes', 50],
  ['Survive Nothing', 'Go 60 seconds in a match without being hit.', 'best_noHitTime', 60],
  ['Do Absolutely Nothing', 'Stand still for 90 seconds in the hub.', 'best_idle', 90],
  ['Do Even Less', 'Stand still for 3 minutes in the hub.', 'best_idle', 180],
  ['Do More Nothing', 'Stand still for 10 minutes in total.', 'idle', 600],
  ['Maximum Nothing', 'Stand still for 30 minutes in total.', 'idle', 1800],
  ['The Nothing Master', 'Stand still for an hour in total.', 'idle', 3600],
  ['Exist', 'Play for a minute.', 'playtime', 60],
  ['Continue Existing', 'Play for 10 minutes.', 'playtime', 600],
  ['Exist Again', 'Play on 2 different days.', 'days', 2],
  ['Congratulations, You Exist', 'Play on 7 different days.', 'days', 7],
  ['Blink', 'Look away from the game and come back.', 'lookAway', 1],
  ["Don't Blink", 'Finish a match without looking away.', 'focusMatches', 1],
  ['Blink Again', 'Look away 10 times.', 'lookAway', 10],
  ['You Blinked', 'Look away 50 times.', 'lookAway', 50],
  ['Stare at the Screen', 'Stare at the achievements board for 30 seconds.', 'achStare', 1],
  ['Look Away', 'Look away in the middle of a match.', 'matchLookAway', 1],
  ['Look Back', 'Look away 3 times.', 'lookAway', 3],
  ['What Were We Doing?', 'Stand still for 5 minutes in the hub.', 'best_idle', 300],
  ['I Forgot', 'Come back after more than an hour away.', 'longReturn', 1],
  q(650, 'Achievement 650'),

  // 🏆 Legendary 651–1001
  ['Bronze Fighter', 'Get 25 knockouts.', 'kos', 25],
  ['Silver Fighter', 'Get 100 knockouts.', 'kos', 100],
  ['Gold Fighter', 'Get 250 knockouts.', 'kos', 250],
  ['Platinum Fighter', 'Get 500 knockouts.', 'kos', 500],
  ['Diamond Fighter', 'Get 1,000 knockouts.', 'kos', 1000],
  ['Master Fighter', 'Get 2,000 knockouts.', 'kos', 2000],
  ['Grandmaster', 'Get 3,000 knockouts.', 'kos', 3000],
  ['Ultimate Fighter', 'Get 5,000 knockouts.', 'kos', 5000],
  ['Arena Master', 'Visit 45 arenas.', 'maps', 45],
  ['Jump Master', 'Jump 20,000 times.', 'jumps', 20000],
  ['KO Master', 'Get 1,500 knockouts.', 'kos', 1500],
  ['Dodge Master', 'Dodge 1,000 attacks.', 'dodges', 1000],
  ['Survival Master', 'Survive 5 minutes in one match.', 'best_survive', 300],
  ['Challenge Master', 'Win 200 challenges.', 'chWon', 200],
  ['Secret Master', 'Find every secret.', 'secretsFound', TOTAL_SECRETS],
  ['Chaos Master', 'See 1,000 events.', 'eventsSeen', 1000],
  ['Physics Master', 'Get launched 1,000 times.', 'launched', 1000],
  ['Movement Master', 'Travel 1,000,000 in total.', 'distance', 1000000],
  ['Combat Master', 'Pop 5,000 balloons.', 'balloonsPopped', 5000],
  ['Game Master', 'Unlock 650 achievements.', 'ach', 650],
  ['100 Matches', 'Play 100 matches.', 'matches', 100],
  ['250 Matches', 'Play 250 matches.', 'matches', 250],
  ['500 Matches', 'Play 500 matches.', 'matches', 500],
  ['1,000 Matches', 'Play 1,000 matches.', 'matches', 1000],
  ['2,500 Matches', 'Play 2,500 matches.', 'matches', 2500],
  ['5,000 Matches', 'Play 5,000 matches.', 'matches', 5000],
  ['10,000 Matches', 'Play 10,000 matches.', 'matches', 10000],
  ['2,500 KOs', 'Get 2,500 knockouts.', 'kos', 2500],
  ['5,000 KOs', 'Get 5,000 knockouts.', 'kos', 5000],
  ['10,000 KOs', 'Get 10,000 knockouts.', 'kos', 10000],
  ['25,000 Jumps', 'Jump 25,000 times.', 'jumps', 25000],
  ['50,000 Jumps', 'Jump 50,000 times.', 'jumps', 50000],
  ['100,000 Jumps', 'Jump 100,000 times.', 'jumps', 100000],
  ['1,000 Dodges', 'Dodge 1,000 attacks.', 'dodges', 1000],
  ['5,000 Dodges', 'Dodge 5,000 attacks.', 'dodges', 5000],
  ['10,000 Dodges', 'Dodge 10,000 attacks.', 'dodges', 10000],
  ['100 Wins', 'Win 100 matches.', 'wins', 100],
  ['250 Wins', 'Win 250 matches.', 'wins', 250],
  ['500 Wins', 'Win 500 matches.', 'wins', 500],
  ['1,000 Wins', 'Win 1,000 matches.', 'wins', 1000],
  ['100 Challenges', 'Win 100 challenges.', 'chWon', 100],
  ['250 Challenges', 'Win 250 challenges.', 'chWon', 250],
  ['500 Challenges', 'Win 500 challenges.', 'chWon', 500],
  ['Every Secret', 'Find every secret.', 'secretsFound', TOTAL_SECRETS],
  ['Every Arena', 'Visit every handmade arena.', 'presetsVisited', PRESET_MAP_COUNT],
  ['Every Character', 'Play matches in 50 different costumes.', 'costumesWorn', 50],
  ['Every Cosmetic', 'Own every costume.', 'costumesOwned', ALL_COSTUMES],
  ['Every Emote', 'Do all 5 emotes.', 'emoteTypes', 5],
  ['Every Achievement', 'Unlock 990 achievements.', 'ach', 990],
  ['Achievement Hoarder', 'Unlock 150 achievements.', 'ach', 150],
  ['Achievement Goblin', 'Unlock 200 achievements.', 'ach', 200],
  ['Achievement Dragon', 'Unlock 300 achievements.', 'ach', 300],
  ['Achievement Wizard', 'Unlock 400 achievements.', 'ach', 400],
  ['Achievement Overlord', 'Unlock 550 achievements.', 'ach', 550],
  ['Achievement Emperor', 'Unlock 650 achievements.', 'ach', 650],
  ['Achievement God', 'Unlock 750 achievements.', 'ach', 750],
  ['The Collector', 'Unlock 800 achievements.', 'ach', 800],
  ['The Completionist', 'Unlock 850 achievements.', 'ach', 850],
  ['The Ultimate Completionist', 'Unlock 900 achievements.', 'ach', 900],
  ['The Impossible Completionist', 'Unlock 925 achievements.', 'ach', 925],
  ['The Legendary Completionist', 'Unlock 950 achievements.', 'ach', 950],
  ['The Final Completionist', 'Unlock 975 achievements.', 'ach', 975],
  ['One Million Points', 'Score 1,000,000 points in total.', 'points', 1000000],
  ['Maximum Score', 'Score 5,000 points in one match.', 'best_score', 5000],
  ['Maximum Chaos', 'See every event.', 'eventTypes', EVENT_TYPES],
  ['Maximum Bonk', 'Pop 10,000 balloons.', 'balloonsPopped', 10000],
  ['Maximum Jump', 'Get 700 high in the air.', 'best_height', 700],
  ['Maximum Speed', 'Dash 5,000 times.', 'dashes', 5000],
  ['Maximum Combo', 'Hit 5 ducks within 5 seconds.', 'fastHits5', 1],
  ['Maximum Everything', 'Unlock 990 achievements.', 'ach', 990],
  ['Perfect Match', 'Win flawless with 5 knockouts.', 'perfectMatches', 1],
  ['Perfect Victory', 'Win 25 matches without losing a balloon.', 'winsFlawless', 25],
  ['Perfect Streak', 'Win 3 flawless matches in a row.', 'best_flawlessStreak', 3],
  ['Perfect Run', 'Finish the Hard obby without falling.', 'obbyHardNoFall', 1],
  ['Perfect Player', 'Get 10 perfect matches.', 'perfectMatches', 10],
  ['Never Fall', 'Finish 10 matches in a row without falling off.', 'best_noFallStreak', 10],
  ['Never Lose', 'Win 10 in a row.', 'bestWinStreak', 10],
  ['Never Stop', 'Play for 10 hours in total.', 'playtime', 36000],
  ['Never Give Up', 'Play again after losing 10 times.', 'again', 10],
  ['Always Jump', 'Jump 300 times in one match.', 'best_jumps', 300],
  ['Always Move', 'Keep moving for 3 minutes.', 'best_moveStreak', 180],
  ['Always Bonk', 'Swing your hammer 25,000 times.', 'swings', 25000],
  ['Always Win', 'Win 25 in a row.', 'bestWinStreak', 25],
  ['The Unstoppable', 'Get 150 knockouts in a row without being knocked out.', 'best_koNoOut', 150],
  ['The Untouchable', 'Finish 25 matches without being hit.', 'noHitMatches', 25],
  ['The Unbeatable', 'Win 2,000 matches.', 'wins', 2000],
  ['The Unbreakable', 'Win 100 matches without losing a balloon.', 'winsFlawless', 100],
  ['The Uncatchable', 'Dodge 20,000 attacks.', 'dodges', 20000],
  ['The Unbonkable', 'Block 1,000 attacks with your shield.', 'blocks', 1000],
  ['The Jumping Legend', 'Jump 250,000 times.', 'jumps', 250000],
  ['The Knockout Legend', 'Get 25,000 knockouts.', 'kos', 25000],
  ['The Arena Legend', 'Win on 40 different arenas.', 'winMaps', 40],
  ['The Chaos Legend', 'See 5,000 events.', 'eventsSeen', 5000],
  ['The Physics Legend', 'Get launched 10,000 times.', 'launched', 10000],
  ['The Secret Legend', 'Find every secret and win on The Void.', 'winMap_void', 1],
  ['The Ultimate Legend', 'Unlock 995 achievements.', 'ach', 995],
  ['Beyond Legendary', 'Score 10,000,000 points in total.', 'points', 10000000],
  ['Beyond Impossible', 'Win the Ultimate challenge 10 times.', 'ch_ultimate', 10],
  ['Beyond Everything', 'Play for 100 hours in total.', 'playtime', 360000],
  ['THE FINAL BONK', 'Land the winning knockout 1,000 times.', 'finalBlow', 1000],
  ['THE FINAL JUMP', 'Jump 300,000 times.', 'jumps', 300000],
  ['THE FINAL WIN', 'Win 5,000 matches.', 'wins', 5000],
  ['THE FINAL FALL', 'Fall off 10,000 times.', 'falls', 10000],
  ['THE FINAL DODGE', 'Dodge 50,000 attacks.', 'dodges', 50000],
  ['THE FINAL ARENA', 'Win on 48 different arenas.', 'winMaps', 48],
  ['THE FINAL SECRET', 'Use the developer computer after finding every other secret.', 'secret_final', 1, true],
  ['THE FINAL CHALLENGE', 'Win the Ultimate challenge 25 times.', 'ch_ultimate', 25],
  ['THE FINAL MATCH', 'Play 20,000 matches.', 'matches', 20000],
  ['THE FINAL ACHIEVEMENT', 'Unlock 998 achievements.', 'ach', 998],
  ['THE REAL FINAL ACHIEVEMENT', 'Unlock 999 achievements.', 'ach', 999],
  q(761, "WAIT, THERE'S MORE"),
  q(762, 'STILL GOING'),
  q(763, 'HOW ARE YOU STILL PLAYING?'),
  q(764, 'YOU FOUND 764'),
  q(765, 'KEEP COUNTING'),
  q(766, '766'),
  q(767, '767'),
  q(768, '768'),
  q(769, '769'),
  q(770, 'Nice Number'),
  q(771, "770 Wasn't Enough"),
  q(772, 'Achievementception'),
  q(773, 'Achievement Inside Achievement'),
  q(774, 'Achievement²'),
  q(775, 'Achievement³'),
  q(776, 'Achievement Overload'),
  q(777, 'Lucky 777'),
  q(778, 'Unlucky 778'),
  q(779, 'One Away'),
  q(780, 'Almost 800'),
  q(781, '800!'),
  q(782, '800 Achievements'),
  q(783, 'The Long Haul'),
  q(784, 'Still Here'),
  q(785, 'Still Bonking'),
  q(786, 'Still Jumping'),
  q(787, 'Still Winning'),
  q(788, 'Still Losing'),
  q(789, 'Still Playing'),
  q(790, 'Why?'),
  q(791, "Because It's Fun"),
  q(792, 'Fair Enough'),
  q(793, 'One Hundred More'),
  q(794, 'Ninety-Nine More'),
  q(795, 'Almost Done'),
  q(796, 'Nearly There'),
  q(797, 'So Close'),
  q(798, 'Two More'),
  q(799, 'One More'),
  q(800, '800th Achievement'),
]
for (let n = 801; n <= 999; n++) LIST.push(n === 900 ? ['900 ACHIEVEMENTS?!', 'Unlock 900 achievements.', 'ach', 900] : q(n))
LIST.push(['ONE THOUSAND!', 'Quack 1,000 times.', 'quacks', 1000])
LIST.push(['THE ULTIMATE BONK', 'Unlock every other achievement. 🏆💥', 'ach', 1000])

export const ACHIEVEMENTS = LIST.map(([name, desc, stat, n, hidden], i) => ({
  id: i + 1,
  name,
  desc,
  stat,
  n,
  hidden: !!hidden,
  reward: n >= 1000 || stat === 'ach' ? 100 : 25,
}))

export const ACH_CATEGORIES = [
  ['🌱 Beginner', 1, 50],
  ['💥 Knockout', 51, 100],
  ['🦘 Jump', 101, 150],
  ['🏃 Movement', 151, 200],
  ['👑 Victory', 201, 250],
  ['😂 Funny', 251, 350],
  ['🗺️ Arena', 351, 400],
  ['🎯 Challenge', 401, 450],
  ['🔥 Streak', 451, 500],
  ['👻 Secret', 501, 550],
  ['🎮 Gameplay', 551, 600],
  ['🤪 Extremely Weird', 601, 650],
  ['🏆 Legendary', 651, 1001],
]

// Stats that are counted from lists in the save instead of stored numbers.
export function derivedStat(save, key) {
  switch (key) {
    case 'ach':
      return Object.keys(save.ach).length
    case 'maps':
      return save.maps.length
    case 'secretsFound':
      return save.secrets.length
    case 'costumesOwned':
      return save.owned.length
    case 'emoteTypes':
      return save.emotes.length
    default:
      return save.stats[key] || 0
  }
}

// Returns the newly unlocked achievements (and records them in the save).
export function checkAchievements(save) {
  const fresh = []
  let changed = true
  while (changed) {
    changed = false
    for (const a of ACHIEVEMENTS) {
      if (save.ach[a.id]) continue
      let value = derivedStat(save, a.stat)
      // "Unlock N achievements" never counts itself.
      if (a.stat === 'ach' && a.n >= 1000) value = Object.keys(save.ach).length
      if (value >= a.n) {
        save.ach[a.id] = Date.now()
        save.bb += a.reward
        fresh.push(a)
        changed = true
      }
    }
  }
  return fresh
}
