// Costume catalogue. `acc` lists the 3D accessories stuck onto the duck,
// `body`/`beak` recolour it and `mat` swaps in a special material.
// `need` is an extra requirement on top of the price: [statKey, amount, text].
const c = (key, name, price, body, acc = [], extra = {}) => ({ key, name, price, body, acc, ...extra })

export const COSTUME_CATEGORIES = [
  {
    key: 'classic',
    name: '🧑 Classic',
    items: [
      c('rookie', 'Rookie', 0, '#ffd23f'),
      c('champion', 'Champion', 500, '#ffd23f', ['crown'], { accColor: '#ff5a5a' }),
      c('ninja', 'Ninja', 1000, '#2b2b3a', ['ninjaBand'], { accColor: '#e53935' }),
      c('pirate', 'Pirate', 750, '#ffd23f', ['pirateHat', 'eyepatch']),
      c('knight', 'Knight', 1250, '#ffd23f', ['knightHelmet'], { accColor: '#b0bec5' }),
      c('wizard', 'Wizard', 1500, '#7e57c2', ['wizardHat'], { accColor: '#3949ab' }),
      c('robot', 'Robot', 2000, '#90a4ae', ['antenna', 'robotFace'], { mat: 'metal' }),
      c('astronaut', 'Astronaut', 2500, '#f5f5f5', ['spaceDome']),
      c('cowboy', 'Cowboy', 1000, '#ffd23f', ['cowboyHat'], { accColor: '#8d5a2b' }),
      c('superhero', 'Superhero', 3000, '#1e88e5', ['cape', 'mask'], { accColor: '#e53935' }),
      c('detective', 'Detective', 1500, '#ffd23f', ['deerstalker', 'monocle'], { accColor: '#8d6e63' }),
      c('scientist', 'Scientist', 1250, '#fafafa', ['goggles', 'hairTuft'], { accColor: '#4dd0e1' }),
      c('chef', 'Chef', 750, '#ffd23f', ['chefHat']),
      c('construction', 'Construction Worker', 900, '#ffd23f', ['hardHat'], { accColor: '#ffb300' }),
      c('firefighter', 'Firefighter', 1500, '#ffd23f', ['hardHat'], { accColor: '#e53935' }),
      c('police', 'Police Officer', 1500, '#ffd23f', ['policeCap'], { accColor: '#1a237e' }),
      c('adventurer', 'Adventurer', 1750, '#ffd23f', ['explorerHat', 'backpack'], { accColor: '#a1887f' }),
      c('explorer', 'Explorer', 1250, '#ffd23f', ['explorerHat'], { accColor: '#d7ccc8' }),
      c('racer', 'Race Car Driver', 2000, '#ffd23f', ['racingHelmet'], { accColor: '#e53935' }),
      c('pilot', 'Pilot', 2000, '#ffd23f', ['pilotCap', 'goggles'], { accColor: '#6d4c41' }),
    ],
  },
  {
    key: 'silly',
    name: '😂 Silly',
    items: [
      c('banana', 'Banana', 500, '#ffe135', ['stem'], { accColor: '#6d4c41' }),
      c('potato', 'Potato', 250, '#c8a165', ['spots'], { accColor: '#8d6e63', beak: '#c8a165' }),
      c('hotdog', 'Hot Dog', 750, '#e57373', ['bun', 'mustard']),
      c('hamburger', 'Hamburger', 1000, '#8d5a2b', ['burgerTop', 'lettuce']),
      c('pizza', 'Pizza', 1250, '#ffca28', ['pizzaHat', 'pepperoni']),
      c('taco', 'Taco', 900, '#ffca28', ['tacoShell', 'lettuce']),
      c('icecream', 'Ice Cream', 750, '#f8bbd0', ['scoop', 'cherry'], { accColor: '#fff59d' }),
      c('donut', 'Donut', 600, '#d7a86e', ['donutRing'], { accColor: '#f06292' }),
      c('popcorn', 'Popcorn', 800, '#fff8e1', ['popcornBucket']),
      c('watermelon', 'Watermelon', 700, '#ef5350', ['rind', 'seeds']),
      c('egg', 'Egg', 300, '#fffdf5', ['eggShell']),
      c('toast', 'Toast', 400, '#e0a96d', ['toastSlice']),
      c('cheese', 'Cheese', 500, '#ffd54f', ['holes']),
      c('pickle', 'Pickle', 650, '#7cb342', ['bumps'], { beak: '#558b2f' }),
      c('cupcake', 'Cupcake', 700, '#f48fb1', ['cupWrapper', 'cherry']),
      c('chicken', 'Giant Chicken', 2000, '#fafafa', ['comb', 'wattle'], { scale: 1.2 }),
      c('rubberduck', 'Rubber Duck', 1000, '#ffeb3b', ['shine']),
      c('cone', 'Traffic Cone', 1500, '#ffd23f', ['trafficCone']),
      c('trashcan', 'Trash Can', 1750, '#ffd23f', ['trashCan']),
      c('toilet', 'Toilet', 2500, '#ffd23f', ['toilet']),
      c('cart', 'Shopping Cart', 2000, '#ffd23f', ['cart']),
      c('box', 'Cardboard Box', 1250, '#ffd23f', ['cardboardBox']),
      c('pencil', 'Giant Pencil', 1500, '#ffd23f', ['pencil']),
      c('peel', 'Banana Peel', 800, '#ffd23f', ['bananaPeel']),
      c('sock', 'Walking Sock', 600, '#eceff1', ['sockStripes'], { accColor: '#e53935' }),
      c('backpack', 'Backpack', 500, '#ffd23f', ['backpack'], { accColor: '#42a5f5' }),
      c('trafficlight', 'Traffic Light', 1800, '#ffd23f', ['trafficLight']),
      c('lamp', 'Lamp', 1000, '#ffd23f', ['lampShade']),
      c('chair', 'Chair', 2000, '#ffd23f', ['chair']),
      c('ball', 'Bouncy Ball', 2500, '#ff4081', ['ballStripe'], { accColor: '#ffeb3b', beak: '#ff4081' }),
    ],
  },
  {
    key: 'creatures',
    name: '👾 Creatures',
    items: [
      c('alien', 'Alien', 1500, '#76ff03', ['antenna', 'bigEyes']),
      c('slime', 'Slime Monster', 2000, '#64dd17', ['drips'], { mat: 'slime' }),
      c('littledragon', 'Little Dragon', 3000, '#43a047', ['wings', 'spikes'], { accColor: '#c0ca33' }),
      c('bigdragon', 'Big Dragon', 5000, '#c62828', ['wings', 'spikes', 'horns'], { accColor: '#ffb300', scale: 1.25 }),
      c('skeleton', 'Skeleton', 2500, '#fafafa', ['ribs'], { accColor: '#212121' }),
      c('ghost', 'Ghost', 2000, '#ffffff', ['sheet'], { mat: 'ghost' }),
      c('vampire', 'Vampire', 3000, '#eceff1', ['cape', 'fangs'], { accColor: '#212121' }),
      c('werewolf', 'Werewolf', 3500, '#6d4c41', ['wolfEars', 'fur'], { accColor: '#4e342e' }),
      c('mummy', 'Mummy', 2500, '#efebe9', ['bandages'], { accColor: '#d7ccc8' }),
      c('monster', 'Frankenstein-style Monster', 3000, '#81c784', ['flatTop', 'bolts'], { accColor: '#212121' }),
      c('blob', 'Blob', 1750, '#ba68c8', ['drips'], { mat: 'slime' }),
      c('mushroom', 'Mushroom', 1000, '#fff3e0', ['mushroomCap'], { accColor: '#e53935' }),
      c('frog', 'Frog', 750, '#66bb6a', ['frogEyes'], { beak: '#e57373' }),
      c('cat', 'Cat', 750, '#ffb74d', ['catEars', 'whiskers']),
      c('dog', 'Dog', 750, '#a1887f', ['dogEars'], { accColor: '#6d4c41' }),
      c('penguin', 'Penguin', 1000, '#263238', ['belly']),
      c('shark', 'Shark', 2500, '#78909c', ['fin', 'teeth']),
      c('croc', 'Crocodile', 2000, '#558b2f', ['ridges', 'teeth']),
      c('turtle', 'Turtle', 1250, '#9ccc65', ['shell'], { accColor: '#6d4c41' }),
      c('bee', 'Bee', 1000, '#ffca28', ['stripes', 'wings', 'antenna'], { accColor: '#212121' }),
      c('butterfly', 'Butterfly', 1500, '#ce93d8', ['butterflyWings', 'antenna'], { accColor: '#29b6f6' }),
      c('spider', 'Spider', 1500, '#37474f', ['legs', 'bigEyes'], { accColor: '#212121' }),
      c('crab', 'Crab', 1250, '#ef5350', ['claws']),
      c('octopus', 'Octopus', 2000, '#ab47bc', ['tentacles']),
    ],
  },
  {
    key: 'fancy',
    name: '🏆 Fancy',
    items: [
      c('goldchamp', 'Golden Champion', 10000, '#ffd700', ['crown'], { mat: 'gold' }),
      c('diamondchamp', 'Diamond Champion', 25000, '#b3e5fc', ['crown'], { mat: 'diamond' }),
      c('platinumchamp', 'Platinum Champion', 50000, '#e0e0e0', ['crown', 'cape'], { mat: 'platinum' }),
      c('king', 'Royal King', 7500, '#ffd23f', ['crown', 'cape'], { accColor: '#8e24aa' }),
      c('queen', 'Royal Queen', 7500, '#ffd23f', ['tiara', 'cape'], { accColor: '#d81b60' }),
      c('prince', 'Crown Prince', 6000, '#ffd23f', ['smallCrown', 'cape'], { accColor: '#1e88e5' }),
      c('emperor', 'Emperor', 10000, '#ffd23f', ['bigCrown', 'cape'], { accColor: '#b71c1c' }),
      c('suit', 'Fancy Suit', 3000, '#ffd23f', ['suit', 'bowtie'], { accColor: '#37474f' }),
      c('tuxedo', 'Tuxedo', 3500, '#ffd23f', ['tophat', 'suit', 'bowtie'], { accColor: '#111111' }),
      c('goldknight', 'Golden Knight', 12500, '#ffd700', ['knightHelmet'], { mat: 'gold', accColor: '#ffd700' }),
      c('crystalwizard', 'Crystal Wizard', 15000, '#80deea', ['wizardHat'], { mat: 'crystal', accColor: '#4dd0e1' }),
      c('spacecaptain', 'Space Captain', 8000, '#eceff1', ['captainHat', 'cape'], { accColor: '#283593' }),
      c('galaxyhero', 'Galaxy Hero', 20000, '#311b92', ['cape', 'mask'], { mat: 'galaxy', accColor: '#7c4dff' }),
      c('neonrobot', 'Neon Robot', 7500, '#00e5ff', ['antenna', 'robotFace'], { mat: 'neon' }),
      c('rainbow', 'Rainbow Warrior', 10000, '#ff4081', ['knightHelmet'], { mat: 'rainbow' }),
    ],
  },
  {
    key: 'game',
    name: '🎮 Game-Themed',
    items: [
      c('8bit', '8-Bit Hero', 2500, '#ffd23f', ['pixelHair', 'pixelSword'], { mat: 'pixel' }),
      c('pixelknight', 'Pixel Knight', 3000, '#90a4ae', ['knightHelmet'], { mat: 'pixel' }),
      c('glitch', 'Glitch', 5000, '#e040fb', [], { mat: 'glitch' }),
      c('error', 'Error', 7500, '#ef5350', ['errorSign']),
      c('loading', 'Loading Screen', 4000, '#ffd23f', ['spinner']),
      c('controller', 'Controller', 3500, '#ffd23f', ['controllerHat']),
      c('arcade', 'Arcade Machine', 5000, '#ffd23f', ['arcadeCabinet']),
      c('retro', 'Retro Gamer', 3000, '#ffd23f', ['backwardsCap', 'headset'], { accColor: '#e53935' }),
      c('speedrunner', 'Speedrunner', 6000, '#ffd23f', ['ninjaBand', 'stopwatch'], { accColor: '#00e676' }),
      c('goblin', 'Achievement Goblin', 10001, '#9ccc65', ['goblinEars', 'trophy']),
    ],
  },
  {
    key: 'refs',
    name: '🥚 Easter Eggs',
    items: [
      c('noob', 'Classic Noob', 100, '#ffd23f', ['suit'], { accColor: '#1e88e5' }),
      c('jellybean', 'Crowned Jellybean', 3000, '#ff9ecf', ['crown']),
      c('plumber', 'Jumpy Plumber', 3500, '#ffd23f', ['cap', 'mustache', 'suit'], { accColor: '#e53935' }),
      c('hedgehog', 'Speedy Hedgehog', 4000, '#1e63d6', ['spikes'], { accColor: '#1e63d6', beak: '#f5d0a9' }),
      c('crewmate', 'Sus Crewmate', 2500, '#e53935', ['visor', 'backpack'], { accColor: '#b71c1c' }),
      c('blockbuilder', 'Block Builder', 2500, '#3fa7d6', ['pixelHair'], { mat: 'pixel' }),
      c('creeper', 'Sssneaky Block', 3000, '#4caf50', ['bigEyes'], { mat: 'pixel', beak: '#2e7d32' }),
      c('pizzabear', 'Pizzeria Bear', 4500, '#8d5a2b', ['tophat', 'bowtie', 'dogEars'], { accColor: '#5d3a1a' }),
      c('tunic', 'Green Tunic Hero', 4000, '#ffd23f', ['wizardHat', 'pixelSword'], { accColor: '#2e7d32' }),
      c('portalduck', 'Test Subject', 3500, '#eceff1', ['goggles', 'backpack'], { accColor: '#ff9800' }),
    ],
  },
  {
    key: 'circus',
    name: '🎪 Digital Circus',
    items: [
      c('jester', 'Jester Duck', 3000, '#e53935', ['jesterHat', 'bowtie'], { accColor: '#1e63d6' }),
      c('ringmaster', 'Ringmaster Duck', 5000, '#e53935', ['tophat', 'bigGrin', 'cape'], { accColor: '#111111' }),
      c('purplebunny', 'Purple Bunny Duck', 3500, '#7b5cd6', ['bunnyEars', 'bigGrin'], { accColor: '#7b5cd6' }),
      c('ragdoll', 'Ragdoll Duck', 2500, '#f48fb1', ['buttonEye', 'hairTuft'], { accColor: '#e53935' }),
      c('chessking', 'Chess King Duck', 4000, '#6d4c41', ['crown', 'bigEyes']),
      c('maskduck', 'Mask Duck', 3000, '#f8bbd0', ['comedyMask'], { accColor: '#ffffff' }),
    ],
  },
  {
    key: 'finds',
    name: '💎 Secret Finds',
    // Can't be bought: each one unlocks by itself when you discover its secret.
    items: [
      c('goldenrubber', 'Golden Rubber Duck', null, '#ffd700', ['shine'], { mat: 'gold', unlock: ['egg_goldduck', 1, 'Say hi to the golden duck hiding inside the tower'] }),
      c('voidduck', 'Void Duck', null, '#1a0033', ['bigEyes'], { mat: 'galaxy', unlock: ['wellDives', 5, 'Dive into the well 5 times'] }),
      c('cakeduck', 'Cake Duck', null, '#f8bbd0', ['cupWrapper', 'cherry'], { unlock: ['egg_cake', 3, 'Eat the cake in the secret room 3 times'] }),
      c('impostor', 'The Impostor', null, '#e53935', ['visor', 'horns', 'backpack'], { accColor: '#b71c1c', unlock: ['egg_vent', 5, 'Use the vent 5 times'] }),
      c('creeperking', 'Creeper King', null, '#4caf50', ['bigEyes', 'crown'], { mat: 'pixel', unlock: ['egg_creeper', 3, 'Get blown up by the hissing block 3 times'] }),
      c('konami', 'Konami Commando', null, '#8d6e63', ['ninjaBand', 'pixelSword'], { mat: 'pixel', accColor: '#e53935', unlock: ['konami', 1, 'Enter a very famous cheat code in the hub'] }),
      c('ghostwell', 'Ghost of the Well', null, '#ffffff', ['sheet'], { mat: 'ghost', unlock: ['egg_boo', 1, 'Type a spooky word in the hub'] }),
      c('luckyduck', 'Lucky Duck', null, '#2bd96b', ['tophat', 'shine'], { unlock: ['egg_wish', 10, 'Make 10 wishes at the fountain'] }),
      c('legendhero', 'Hero of Legend', null, '#ffd23f', ['wizardHat', 'pixelSword'], { accColor: '#1565c0', unlock: ['egg_sword', 1, 'Pull the sword from the stone'] }),
      c('diamondminer', 'Diamond Miner', null, '#4dd0e1', ['hardHat'], { mat: 'diamond', accColor: '#ffb300', unlock: ['egg_diamond', 1, 'Find diamonds on a hidden platform'] }),
      c('herobrine', 'Herobrine?', null, '#3fa7d6', ['pixelHair', 'glowEyes'], { mat: 'pixel', unlock: ['egg_herobrine', 1, 'Knock out a very rare, very mysterious bot'] }),
      c('moonduck', 'Moon Duck', null, '#cfd8dc', ['spaceDome'], { unlock: ['best_height', 600, 'Get REALLY high up'] }),
      c('nightowl', 'Night Owl', null, '#5d4037', ['bigEyes', 'wolfEars'], { accColor: '#3e2723', unlock: ['nightMatches', 5, 'Play 5 matches at night'] }),
      c('bigrubber', 'Big Rubber Duck', null, '#ffeb3b', ['shine'], { scale: 1.35, unlock: ['survive_duck', 3, 'Survive the giant rubber duck 3 times'] }),
      c('goldrunner', 'Golden Speedrunner', null, '#ffd700', ['ninjaBand', 'stopwatch'], { mat: 'gold', accColor: '#00e676', unlock: ['obbyHardFast', 1, 'Finish the Hard obby in under 60 seconds'] }),
      c('abstracted', 'Abstracted Duck', null, '#111111', ['bigEyes'], { mat: 'glitch', unlock: ['egg_exit', 5, 'Keep looking for the EXIT'] }),
      c('buttonmasher', 'Button Masher', null, '#ff2d2d', ['mysteryBox'], { unlock: ['redButton', 100, 'Press the big red button 100 times'] }),
    ],
  },
  {
    key: 'secret',
    name: '💀 SECRET',
    items: [
      c('invisible', 'Invisible Costume', null, '#ffffff', [], {
        mat: 'invisible',
        need: ['secretsFound', 10, 'Find 10 secrets in the hub'],
      }),
      c('shadow', 'Shadow', 25000, '#111111', [], { mat: 'shadow' }),
      c('goldenglitch', 'Golden Glitch', 50000, '#ffd700', [], { mat: 'goldglitch' }),
      c('qqq', '??? Costume', null, '#9e9e9e', ['questionMark'], {
        need: ['ach', 500, 'Unlock 500 achievements'],
      }),
      c('error404', 'Error 404', 40404, '#212121', ['errorSign'], { mat: 'glitch' }),
      c('questionmark', 'Question Mark', 9999, '#7c4dff', ['questionMark']),
      c('mysterybox', 'Mystery Box', null, '#ffd23f', ['mysteryBox'], {
        need: ['mysteryBoxes', 25, 'Open 25 Mystery Boxes in matches'],
      }),
      c('developer', 'The Developer', 100000, '#ffd23f', ['hoodie', 'glasses', 'headset'], { accColor: '#263238' }),
      c('ultimatebonker', 'Ultimate Bonker', 75000, '#ff6d00', ['bigCrown', 'cape'], {
        mat: 'glow',
        accColor: '#ffd600',
        need: ['kos', 500, 'Get 500 knockouts'],
      }),
      c('champion1001', '1001 Achievement Champion', 1001001, '#ffd700', ['bigCrown', 'cape', 'trophy'], {
        mat: 'rainbow',
        need: ['ach', 1000, 'Unlock every other achievement'],
      }),
    ],
  },
]

export const COSTUMES = Object.fromEntries(
  COSTUME_CATEGORIES.flatMap((cat) => cat.items.map((it) => [it.key, { ...it, cat: cat.key }])),
)

export const PETS = [
  { key: 'duckling', name: 'Duckling', price: 250, kind: 'duckling', color: '#ffe082' },
  { key: 'chick', name: 'Chick', price: 400, kind: 'chick', color: '#fff176' },
  { key: 'frog', name: 'Froggy', price: 600, kind: 'frog', color: '#66bb6a' },
  { key: 'puppy', name: 'Puppy', price: 750, kind: 'puppy', color: '#a1887f' },
  { key: 'kitten', name: 'Kitten', price: 750, kind: 'kitten', color: '#ffb74d' },
  { key: 'bee', name: 'Buzzy Bee', price: 900, kind: 'bee', color: '#ffca28' },
  { key: 'bunny', name: 'Bunny', price: 1000, kind: 'bunny', color: '#f5f5f5' },
  { key: 'penguin', name: 'Penguin', price: 1500, kind: 'penguin', color: '#263238' },
  { key: 'slime', name: 'Slimey', price: 1750, kind: 'slime', color: '#64dd17' },
  { key: 'ghost', name: 'Boo', price: 2000, kind: 'ghost', color: '#ffffff' },
  { key: 'drone', name: 'Robo Drone', price: 3000, kind: 'drone', color: '#90a4ae' },
  { key: 'dragon', name: 'Mini Dragon', price: 5000, kind: 'dragon', color: '#e53935' },
  { key: 'unicorn', name: 'Unicorn', price: 7500, kind: 'unicorn', color: '#f8bbd0' },
  { key: 'goldduckling', name: 'Golden Duckling', price: 25000, kind: 'duckling', color: '#ffd700', mat: 'gold' },
]

export const PET_MAP = Object.fromEntries(PETS.map((p) => [p.key, p]))

// Bot ducks wear random cheaper costumes so matches look colourful.
export const BOT_COSTUMES = Object.values(COSTUMES)
  .filter((c) => c.price !== null && c.price <= 5000 && c.key !== 'rookie')
  .map((c) => c.key)

export const SECRET_UNLOCKS = Object.values(COSTUMES).filter((c) => c.unlock)
